/**
 * Generated by @facadeur/codegen-react from the "form-select" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { FormSelect } from './component';
export type { FormSelectProps, FormSelectState } from './types';
