/**
 * Generated by @facadeur/codegen-react from the "form-select" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type FormSelectState = 'default' | 'focused' | 'disabled';

export interface FormSelectProps {
  label?: string;
  value?: string;
  state?: FormSelectState;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
