/**
 * Generated by @facadeur/codegen-react from the "form-select" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export type FormSelectState = 'default' | 'focused' | 'disabled';

export interface FormSelectData {
  label?: string;
  value?: string;
}

export interface FormSelectProps extends ComponentProps, FormSelectData {
  state?: FormSelectState;
}
