import { type Breakpoint, type DocumentFile } from '@facadeur/core';
import { compileDocument, scopeStyleSelector, type CompiledRule } from '@facadeur/style-engine';
import { renderDesignCss, type DesignInput } from '@facadeur/tokens';
import type { LocalClassNames } from './component/types';
import { instanceNodeIds } from './component/class-names';

const TOKEN_BANNER =
  '/* Generated by @facadeur/codegen-react. Tokens and fonts from the design document. */\n\n';

const COMPONENT_BANNER = `/* Generated by @facadeur/codegen-react.
 * CSS Modules classes are shared with the generated JSX. Token references stay var(--…).
 */

`;

/** Tokens and fonts as one stylesheet. Custom properties sit on `:root`. */
export function renderTokenCss(design?: DesignInput): string {
  const body = renderDesignCss(design ?? {});
  return `${TOKEN_BANNER}${body.endsWith('\n') ? body : `${body}\n`}`;
}

/** Render a document's rules using the same local class mapping as its JSX. */
export function renderDocumentCss(
  document: DocumentFile,
  classNames: LocalClassNames,
  breakpoints?: readonly Breakpoint[],
  catalog: readonly DocumentFile[] = [document],
): string {
  const rootClass = classNames.get(document.root.id);
  if (!rootClass) throw new Error(`Missing local CSS class for root of "${document.id}"`);
  const instances = instanceNodeIds(document);
  const compiled = compileDocument(document, {
    address: 'instance',
    ...(breakpoints?.length ? { breakpoints } : {}),
    catalog,
    selectorForNode: ({
      node,
      nodeId,
      path,
      isRoot,
      targetPath,
      targetComponentId,
      variantScope,
    }) => {
      const moduleScope = `.${rootClass}${variantScope ? `[data-variant="${cssString(variantScope)}"]` : ''}`;
      if (targetPath) {
        return nestedInstanceSelector(moduleScope, targetPath, targetComponentId);
      }
      if (isRoot) return moduleScope;
      if (node.type === 'instance' && document.styles?.children?.[node.id] !== undefined) {
        const instancePath = path?.split('/').slice(1).filter(Boolean).join('/') ?? nodeId;
        return nestedInstanceSelector(moduleScope, instancePath, node.component);
      }
      const className = classNames.get(nodeId);
      return className ? `${moduleScope} .${className}` : moduleScope;
    },
    selectorForVariant: reactVariantSelector,
    selectorForStyleRule: ({ selector, variantScope, axisVariant }) =>
      scopeModuleSelector(selector, rootClass, variantScope, axisVariant),
  });
  const base = compiled.filter((rule) => rule.minWidth === undefined);
  const widths = [
    ...new Set(compiled.flatMap((rule) => (rule.minWidth === undefined ? [] : [rule.minWidth]))),
  ].sort((left, right) => left - right);
  const chunks = [printRules(base, instances, 0)];
  for (const minWidth of widths) {
    const inner = printRules(
      compiled.filter((rule) => rule.minWidth === minWidth),
      instances,
      1,
    );
    if (!inner) continue;
    chunks.push(`@media (min-width: ${minWidth}px) {\n${inner}\n}`);
  }
  const selectors = new Set(
    compiled.flatMap((rule) => rule.selector.match(/\.([A-Za-z_][A-Za-z0-9_-]*)/g) ?? []),
  );
  const exportRules = [...classNames.values()]
    .filter((className) => !selectors.has(`.${className}`))
    .map((className) => `.${className} {}`);
  const body = [...chunks.filter(Boolean), ...exportRules].join('\n\n');
  const layerOrder = '@layer facadeur.components, facadeur.instances, facadeur.nested-instances;';
  return `${COMPONENT_BANNER}${layerOrder}${body ? `\n\n${body}` : ''}${body ? '\n' : ''}`;
}

function nestedInstanceSelector(
  root: string,
  path: string,
  componentId: string | undefined,
): string {
  if (!componentId) throw new Error(`Missing component id for nested style target "${path}"`);
  const segments = path.split('/').filter(Boolean);
  const terminal = segments.at(-1);
  if (!terminal) throw new Error(`Empty nested style target "${path}"`);
  const component = `[data-component="${cssString(componentId)}"]`;
  const chain = segments
    .map((id, index) =>
      index === segments.length - 1
        ? `[data-node="${cssString(id)}"]${component}${component}`
        : `[data-node="${cssString(id)}"]`,
    )
    .join(' > ');
  return `${root} > ${chain}`;
}

function scopeModuleSelector(
  selector: string,
  rootClass: string,
  variant?: string,
  axisVariant?: { axis: string; value: string },
): string {
  const axisAttribute = axisVariant
    ? axisVariant.axis === 'variant'
      ? `[data-variant="${cssString(axisVariant.value)}"]`
      : `[data-variant-${cssString(axisVariant.axis)}="${cssString(axisVariant.value)}"]`
    : '';
  const root = `.${rootClass}${variant ? `[data-variant="${cssString(variant)}"]` : ''}${axisAttribute}`;
  return scopeStyleSelector(selector, root);
}

function cssString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function reactVariantSelector(selector: string, axis: string, value: string): string {
  const attribute =
    axis === 'variant'
      ? `[data-variant="${cssString(value)}"]`
      : `[data-variant-${cssString(axis)}="${cssString(value)}"]`;
  const space = selector.indexOf(' ');
  if (space === -1) return `${selector}${attribute}`;
  return `${selector.slice(0, space)}${attribute}${selector.slice(space)}`;
}

function printRules(
  rules: readonly CompiledRule[],
  instances: ReadonlySet<string>,
  indent: number,
): string {
  const layers = [
    {
      name: 'facadeur.components',
      matches: (rule: CompiledRule) =>
        rule.target.kind !== 'nested-instance' &&
        !rule.styleRuleId &&
        !isInstanceRule(rule, instances),
    },
    {
      name: 'facadeur.instances',
      matches: (rule: CompiledRule) =>
        rule.target.kind !== 'nested-instance' &&
        (rule.styleRuleId !== undefined || isInstanceRule(rule, instances)),
    },
    {
      name: 'facadeur.nested-instances',
      matches: (rule: CompiledRule) => rule.target.kind === 'nested-instance',
    },
  ];
  const innerPad = '  '.repeat(indent);
  return layers
    .map(({ name, matches }) => {
      const body = rules
        .filter(matches)
        .map((rule) => printRule(rule, indent + 1))
        .filter(Boolean)
        .join('\n\n');
      return body ? `${innerPad}@layer ${name} {\n${body}\n${innerPad}}` : '';
    })
    .filter(Boolean)
    .join('\n\n');
}

function isInstanceRule(rule: CompiledRule, instances: ReadonlySet<string>): boolean {
  if (rule.target.kind === 'nested-instance') return false;
  if (rule.styleRuleBindings) {
    return Object.values(rule.styleRuleBindings).some((nodeId) => instances.has(nodeId));
  }
  return rule.target.kind === 'node' && rule.target.isInstance;
}

function printRule(rule: CompiledRule, indent: number): string {
  const pad = '  '.repeat(indent);
  const body = rule.declarations.map(([name, value]) => `${pad}  ${name}: ${value};`).join('\n');
  return `${pad}${rule.selector} {\n${body}\n${pad}}`;
}
