import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmdirSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, isAbsolute, relative, resolve, sep } from 'node:path';
import type { GeneratedFile } from './generate';

const MANIFEST = '.facadeur-codegen-manifest.json';
const GENERATED_MARKER = 'Generated by @facadeur/codegen-react';

interface OutputManifest {
  version: 1;
  files: string[];
}

/**
 * Replace only files owned by this generator. On the first manifest-backed run,
 * legacy generated files are recognized by their banner inside known roots.
 */
export function writeGeneratedFiles(
  directory: string,
  files: readonly GeneratedFile[],
  legacyRoots: readonly string[],
): void {
  const root = resolve(directory);
  const desired = new Map(
    files.map((file) => [safeRelativePath(file.path), file.contents] as const),
  );
  const previous = readManifest(root);
  const managed = previous
    ? new Set(previous.files.map(safeRelativePath))
    : scanLegacyGeneratedFiles(root, legacyRoots);

  for (const path of managed) {
    if (desired.has(path)) continue;
    const target = targetPath(root, path);
    if (!existsSync(target)) continue;
    unlinkSync(target);
    removeEmptyParents(dirname(target), root);
  }

  for (const [path, contents] of desired) {
    const target = targetPath(root, path);
    mkdirSync(dirname(target), { recursive: true });
    if (!existsSync(target) || readFileSync(target, 'utf8') !== contents) {
      writeFileSync(target, contents, 'utf8');
    }
  }

  mkdirSync(root, { recursive: true });
  const manifest: OutputManifest = {
    version: 1,
    files: [...desired.keys()].sort((left, right) => left.localeCompare(right, 'en')),
  };
  const serialized = `${JSON.stringify(manifest, null, 2)}\n`;
  const manifestPath = resolve(root, MANIFEST);
  if (!existsSync(manifestPath) || readFileSync(manifestPath, 'utf8') !== serialized) {
    writeFileSync(manifestPath, serialized, 'utf8');
  }
}

function readManifest(root: string): OutputManifest | null {
  const path = resolve(root, MANIFEST);
  if (!existsSync(path)) return null;
  const value = JSON.parse(readFileSync(path, 'utf8')) as Partial<OutputManifest>;
  if (
    value.version !== 1 ||
    !Array.isArray(value.files) ||
    value.files.some((file) => typeof file !== 'string')
  ) {
    throw new Error(`Invalid codegen manifest "${path}"`);
  }
  return { version: 1, files: value.files };
}

function scanLegacyGeneratedFiles(root: string, legacyRoots: readonly string[]): Set<string> {
  const generated = new Set<string>();
  for (const candidate of legacyRoots) {
    const path = targetPath(root, safeRelativePath(candidate));
    if (!existsSync(path)) continue;
    scan(path, root, generated);
  }
  return generated;
}

function scan(path: string, root: string, generated: Set<string>): void {
  const stat = statSync(path);
  if (stat.isDirectory()) {
    for (const entry of readdirSync(path).sort((left, right) => left.localeCompare(right, 'en'))) {
      scan(resolve(path, entry), root, generated);
    }
    return;
  }
  if (!stat.isFile()) return;
  if (readFileSync(path, 'utf8').includes(GENERATED_MARKER)) {
    generated.add(relative(root, path).split(sep).join('/'));
  }
}

function safeRelativePath(path: string): string {
  const normalized = path.replaceAll('\\', '/').replace(/^\.\/+/, '');
  if (!normalized || isAbsolute(path) || normalized === '..' || normalized.startsWith('../')) {
    throw new Error(`Generated path must stay inside its output directory: "${path}"`);
  }
  return normalized;
}

function targetPath(root: string, path: string): string {
  const target = resolve(root, path);
  const fromRoot = relative(root, target);
  if (fromRoot === '..' || fromRoot.startsWith(`..${sep}`) || isAbsolute(fromRoot)) {
    throw new Error(`Generated path must stay inside its output directory: "${path}"`);
  }
  return target;
}

function removeEmptyParents(start: string, root: string): void {
  let current = start;
  while (current !== root) {
    if (readdirSync(current).length > 0) return;
    rmdirSync(current);
    current = dirname(current);
  }
}
