import {
  resolvePreviewData,
  variantPresets,
  type DocumentFile,
  type FieldDefinition,
  type FieldValue,
} from '@facadeur/core';
import type { ComponentFile, PropSpec } from './component';
import { componentName } from './names';
import { typedStoryValue } from './story-data';

const kindTitles: Record<DocumentFile['kind'], string> = {
  atom: 'Atoms',
  component: 'Components',
  section: 'Sections',
  page: 'Pages',
};

export function generateStories(
  documents: readonly DocumentFile[],
  components: readonly ComponentFile[],
  contracts: ReadonlyMap<string, Map<string, FieldDefinition>>,
): { path: string; contents: string }[] {
  const byId = new Map(documents.map((document) => [document.id, document]));
  return components.map((component) => {
    const document = byId.get(component.id);
    if (!document) {
      throw new Error(`Missing document for component "${component.id}"`);
    }
    return {
      path: `src/stories/generated/${component.component}.stories.tsx`,
      contents: renderStory(document, component, contracts.get(document.id)),
    };
  });
}

function renderStory(
  document: DocumentFile,
  file: ComponentFile,
  contractFields: ReadonlyMap<string, FieldDefinition> | undefined,
): string {
  const title = `${kindTitles[document.kind]}/${file.component}`;
  const argLines = renderArgs(
    file.props,
    resolvePreviewData(document, undefined, contractFields),
    contractFields,
  );
  const lines = [
    '/**',
    ' * Generated by @facadeur/codegen-react.',
    ' * The facadeur JSON is the source of truth. Do not edit by hand.',
    ' */',
    '',
    "import type { Meta, StoryObj } from '@storybook/react';",
    `import { ${file.component} } from '@facadeur/ui';`,
    '',
    'const meta = {',
    `  title: ${quote(title)},`,
    `  component: ${file.component},`,
    "  tags: ['autodocs'],",
  ];
  if (argLines.length) {
    lines.push('  args: {');
    lines.push(...argLines);
    lines.push('  },');
  }
  lines.push(`} satisfies Meta<typeof ${file.component}>;`, '', 'export default meta;', '');
  lines.push(`type Story = StoryObj<typeof meta>;`, '', 'export const Default: Story = {};', '');
  // Named variant props precede ordinary axes in the component contract.
  const variant = file.props.find(
    (prop) => prop.source === 'variant' && prop.fieldType === 'variant',
  );
  const used = new Set(['Default', 'Story', 'meta']);
  if (variant) {
    for (const preset of variantPresets(document).filter((preset) => preset.name !== 'default')) {
      const name = componentName(preset.name, used);
      lines.push(
        `export const ${name}: Story = {`,
        `  name: ${JSON.stringify(document.variantLabels?.[preset.name] ?? preset.name)},`,
        '  args: {',
        ...renderArgs(
          file.props.filter((prop) => prop !== variant),
          resolvePreviewData(document, preset.name, contractFields),
          contractFields,
        ),
        `    ${variant.name}: ${JSON.stringify(preset.name)},`,
        '  },',
        '};',
        '',
      );
    }
  }
  return lines.join('\n');
}

function renderArgs(
  props: readonly PropSpec[],
  preview: Record<string, FieldValue>,
  contracts: ReadonlyMap<string, FieldDefinition> | undefined,
): string[] {
  const lines: string[] = [];
  for (const prop of props) {
    const sample = preview[prop.source];
    const value =
      sample !== undefined && prop.fieldType !== 'event' && prop.fieldType !== 'variant'
        ? JSON.stringify(typedStoryValue(sample, contracts?.get(prop.source)?.schema))
        : (prop.defaultExpr ?? (prop.required ? requiredStoryValue(prop) : undefined));
    if (value !== undefined) lines.push(`    ${prop.name}: ${value},`);
  }
  return lines;
}

function requiredStoryValue(prop: PropSpec): string | undefined {
  switch (prop.fieldType) {
    case 'boolean':
      return 'false';
    case 'number':
      return '0';
    case 'array':
      return '[]';
    case 'object':
      return '{}';
    case 'enum': {
      const first = prop.type.split('|')[0]?.trim();
      return first && first.startsWith("'") ? first : "'Example'";
    }
    case 'text':
    case 'richText':
    case 'image':
    case 'link':
    case 'token':
      return prop.source === 'src' ? "'/placeholder-media'" : "'Example'";
    default:
      return undefined;
  }
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}
