/**
 * Generated by @facadeur/codegen-react from the "form-controls-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { FormControlsSectionProps } from './types';
import { Button } from '../Button';
import { FormFieldRow } from '../FormFieldRow';
import { FormSegmented } from '../FormSegmented';
import { FormSelect } from '../FormSelect';
import { FormTextInput } from '../FormTextInput';
import { FormToggle } from '../FormToggle';
import { Input } from '../Input';
import { Textarea } from '../Textarea';

export function FormControlsSection({
  formFields = [
    { id: 'name', kind: 'input', label: 'Name', placeholder: 'Your name' },
    { id: 'message', kind: 'textarea', label: 'Message', rows: 3 },
    { id: 'property', kind: 'select', label: 'Property' },
    { id: 'enabled', kind: 'toggle', label: 'Use token' },
  ],
  nodeId,
  className,
}: FormControlsSectionProps) {
  return (
    <main
      data-component="form-controls-section"
      data-node={nodeId}
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <header data-node="intro" className={styles['intro']}>
        <p data-node="eyebrow" className={styles['eyebrow']}>
          facadeur · editor kit
        </p>
        <h1 data-node="title" className={styles['title']}>
          Controls
        </h1>
        <p data-node="intro-text" className={styles['intro-text']}>
          A small, token-driven control language for the editor inspector.
        </p>
      </header>
      <section data-node="native-text-controls" className={styles['native-text-controls']}>
        <h2 data-node="native-text-controls-title" className={styles['native-text-controls-title']}>
          Native text controls
        </h2>
        <div data-node="native-text-controls-row" className={styles['native-text-controls-row']}>
          <Input
            nodeId="native-input"
            className={styles['native-input']}
            label="Input"
            value="Value"
          />
          <Textarea
            nodeId="native-textarea"
            className={styles['native-textarea']}
            label="Textarea"
            value="Write a message"
            rows={3}
          />
        </div>
      </section>
      <section data-node="text-inputs" className={styles['text-inputs']}>
        <h2 data-node="text-input-title" className={styles['text-input-title']}>
          Text field states
        </h2>
        <div data-node="text-input-row" className={styles['text-input-row']}>
          <FormTextInput
            nodeId="input-default"
            className={styles['input-default']}
            label="Label"
            value="Button"
            hint="Default"
            state="default"
          />
          <FormTextInput
            nodeId="input-focused"
            className={styles['input-focused']}
            label="Label"
            value="Button"
            hint="Focused"
            hasIcon
            icon="data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 16 16%22%3E%3Ccircle cx=%226.5%22 cy=%226.5%22 r=%223.5%22 fill=%22none%22 stroke=%22%236f675e%22 stroke-width=%221.5%22/%3E%3Cpath d=%22m9.2 9.2 4.2 4.2%22 fill=%22none%22 stroke=%22%236f675e%22 stroke-width=%221.5%22 stroke-linecap=%22round%22/%3E%3C/svg%3E"
            state="focused"
          />
          <FormTextInput
            nodeId="input-invalid"
            className={styles['input-invalid']}
            label="Label"
            value="Button"
            hint="Invalid value"
            state="invalid"
          />
          <FormTextInput
            nodeId="input-disabled"
            className={styles['input-disabled']}
            label="Label"
            value="Disabled"
            hint="Disabled"
            state="disabled"
          />
        </div>
      </section>
      <section data-node="selection" className={styles['selection']}>
        <h2 data-node="selection-title" className={styles['selection-title']}>
          Selection and options
        </h2>
        <div data-node="selection-row" className={styles['selection-row']}>
          <FormSelect
            nodeId="select-default"
            className={styles['select-default']}
            label="Token"
            value="color.text.primary"
            state="default"
          />
          <FormSelect
            nodeId="select-focused"
            className={styles['select-focused']}
            label="Property"
            value="border color"
            state="focused"
          />
          <FormSelect
            nodeId="select-disabled"
            className={styles['select-disabled']}
            label="Breakpoint"
            value="Base"
            state="disabled"
          />
          <FormSegmented
            nodeId="alignment"
            className={styles['alignment']}
            label="Alignment"
            state="start"
          />
          <FormToggle
            nodeId="toggle-on"
            className={styles['toggle-on']}
            label="Use token"
            value="On"
            state="on"
          />
          <FormToggle
            nodeId="toggle-off"
            className={styles['toggle-off']}
            label="Use token"
            value="Off"
            state="off"
          />
          <FormToggle
            nodeId="toggle-disabled"
            className={styles['toggle-disabled']}
            label="Use token"
            value="Disabled"
            state="disabled"
          />
        </div>
      </section>
      <section data-node="field-definition" className={styles['field-definition']}>
        <h2 data-node="field-title" className={styles['field-title']}>
          Field definition
        </h2>
        <p data-node="field-note" className={styles['field-note']}>
          Compact rows keep component definitions scannable; details can open on demand.
        </p>
        <div data-node="field-list" className={styles['field-list']}>
          <div data-node="field-header" className={styles['field-header']}>
            <span data-node="column-name" className={styles['column-name']}>
              Name
            </span>
            <span data-node="column-type" className={styles['column-type']}>
              Type
            </span>
            <span data-node="column-default" className={styles['column-default']}>
              Default
            </span>
          </div>
          <FormFieldRow
            nodeId="field-label"
            className={styles['field-label']}
            name="label"
            type="text"
            value="Button"
          />
          <FormFieldRow
            nodeId="field-tone"
            className={styles['field-tone']}
            name="tone"
            type="enum"
            value="primary"
            state="selected"
          />
          <FormFieldRow
            nodeId="field-disabled"
            className={styles['field-disabled']}
            name="disabled"
            type="boolean"
            value="false"
          />
        </div>
        <Button
          nodeId="add-field"
          className={styles['add-field']}
          label="+ Add field"
          tone="secondary"
          size="sm"
        />
      </section>
      <section data-node="data-driven-form" className={styles['data-driven-form']}>
        <h2 data-node="data-driven-title" className={styles['data-driven-title']}>
          Data-driven form
        </h2>
        {(formFields ?? []).map((field, fieldIndex) => (
          <div data-node="data-form" className={styles['data-form']} key={field?.id ?? fieldIndex}>
            {field?.kind === 'input' && (
              <FormTextInput
                nodeId="data-input"
                className={styles['data-input']}
                label={field?.label}
                hint={field?.hint}
                value={field?.value}
                placeholder={field?.placeholder}
              />
            )}
            {field?.kind === 'textarea' && (
              <Textarea
                nodeId="data-textarea"
                className={styles['data-textarea']}
                label={field?.label}
                value={field?.value}
                placeholder={field?.placeholder}
                rows={field?.rows}
              />
            )}
            {field?.kind === 'select' && (
              <FormSelect
                nodeId="data-select"
                className={styles['data-select']}
                label={field?.label}
                value={field?.value}
              />
            )}
            {field?.kind === 'toggle' && (
              <FormToggle
                nodeId="data-toggle"
                className={styles['data-toggle']}
                label={field?.label}
                value={field?.value}
              />
            )}
          </div>
        ))}
      </section>
    </main>
  );
}
