/**
 * Generated by @facadeur/codegen-react from the "form-controls-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { FormControlsSectionProps } from './types';
import { Button } from '../Button';
import { FormFieldRow } from '../FormFieldRow';
import { FormSegmented } from '../FormSegmented';
import { FormSelect } from '../FormSelect';
import { FormTextInput } from '../FormTextInput';
import { FormToggle } from '../FormToggle';
import { Input } from '../Input';
import { Textarea } from '../Textarea';

export function FormControlsSection({
  formFields = [
    { id: 'name', kind: 'input', label: 'Name', placeholder: 'Your name' },
    { id: 'message', kind: 'textarea', label: 'Message', rows: 3 },
    { id: 'property', kind: 'select', label: 'Property' },
    { id: 'enabled', kind: 'toggle', label: 'Use token' },
  ],
  icon,
  hasIcon,
  disabled,
  placeholder,
  name,
  className,
}: FormControlsSectionProps) {
  return (
    <main
      data-component="form-controls-section"
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <header className={styles['intro']}>
        <p className={styles['eyebrow']}>facadeur · editor kit</p>
        <h1 className={styles['title']}>Controls</h1>
        <p className={styles['intro-text']}>
          A small, token-driven control language for the editor inspector.
        </p>
      </header>
      <section className={styles['native-text-controls']}>
        <h2 className={styles['native-text-controls-title']}>Native text controls</h2>
        <div className={styles['native-text-controls-row']}>
          <Input
            className="FormControlsSection__native-input"
            placeholder={placeholder}
            name={name}
            disabled={disabled}
            label="Input"
            value="Value"
          />
          <Textarea
            className="FormControlsSection__native-textarea"
            placeholder={placeholder}
            name={name}
            label="Textarea"
            value="Write a message"
            rows={3}
          />
        </div>
      </section>
      <section className={styles['text-inputs']}>
        <h2 className={styles['text-input-title']}>Text field states</h2>
        <div className={styles['text-input-row']}>
          <FormTextInput
            className="FormControlsSection__input-default"
            icon={icon}
            hasIcon={hasIcon}
            placeholder={placeholder}
            name={name}
            disabled={disabled}
            label="Label"
            value="Button"
            hint="Default"
            state="default"
          />
          <FormTextInput
            className="FormControlsSection__input-focused"
            placeholder={placeholder}
            name={name}
            disabled={disabled}
            label="Label"
            value="Button"
            hint="Focused"
            hasIcon
            icon="data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 16 16%22%3E%3Ccircle cx=%226.5%22 cy=%226.5%22 r=%223.5%22 fill=%22none%22 stroke=%22%236f675e%22 stroke-width=%221.5%22/%3E%3Cpath d=%22m9.2 9.2 4.2 4.2%22 fill=%22none%22 stroke=%22%236f675e%22 stroke-width=%221.5%22 stroke-linecap=%22round%22/%3E%3C/svg%3E"
            state="focused"
          />
          <FormTextInput
            className="FormControlsSection__input-invalid"
            icon={icon}
            hasIcon={hasIcon}
            placeholder={placeholder}
            name={name}
            disabled={disabled}
            label="Label"
            value="Button"
            hint="Invalid value"
            state="invalid"
          />
          <FormTextInput
            className="FormControlsSection__input-disabled"
            icon={icon}
            hasIcon={hasIcon}
            placeholder={placeholder}
            name={name}
            disabled={disabled}
            label="Label"
            value="Disabled"
            hint="Disabled"
            state="disabled"
          />
        </div>
      </section>
      <section className={styles['selection']}>
        <h2 className={styles['selection-title']}>Selection and options</h2>
        <div className={styles['selection-row']}>
          <FormSelect
            className="FormControlsSection__select-default"
            label="Token"
            value="color.text.primary"
            state="default"
          />
          <FormSelect
            className="FormControlsSection__select-focused"
            label="Property"
            value="border color"
            state="focused"
          />
          <FormSelect
            className="FormControlsSection__select-disabled"
            label="Breakpoint"
            value="Base"
            state="disabled"
          />
          <FormSegmented
            className="FormControlsSection__alignment"
            label="Alignment"
            state="start"
          />
          <FormToggle
            className="FormControlsSection__toggle-on"
            label="Use token"
            value="On"
            state="on"
          />
          <FormToggle
            className="FormControlsSection__toggle-off"
            label="Use token"
            value="Off"
            state="off"
          />
          <FormToggle
            className="FormControlsSection__toggle-disabled"
            label="Use token"
            value="Disabled"
            state="disabled"
          />
        </div>
      </section>
      <section className={styles['field-definition']}>
        <h2 className={styles['field-title']}>Field definition</h2>
        <p className={styles['field-note']}>
          Compact rows keep component definitions scannable; details can open on demand.
        </p>
        <div className={styles['field-list']}>
          <div className={styles['field-header']}>
            <span className={styles['column-name']}>Name</span>
            <span className={styles['column-type']}>Type</span>
            <span className={styles['column-default']}>Default</span>
          </div>
          <FormFieldRow
            className="FormControlsSection__field-label"
            name="label"
            type="text"
            value="Button"
          />
          <FormFieldRow
            className="FormControlsSection__field-tone"
            name="tone"
            type="enum"
            value="primary"
            state="selected"
          />
          <FormFieldRow
            className="FormControlsSection__field-disabled"
            name="disabled"
            type="boolean"
            value="false"
          />
        </div>
        <Button
          className="FormControlsSection__add-field"
          label="+ Add field"
          tone="secondary"
          size="sm"
        />
      </section>
      <section className={styles['data-driven-form']}>
        <h2 className={styles['data-driven-title']}>Data-driven form</h2>
        {(formFields ?? []).map((field, fieldIndex) => (
          <div className={styles['data-form']} key={field?.id ?? fieldIndex}>
            {field?.kind === 'input' && (
              <FormTextInput
                className="FormControlsSection__data-input"
                icon={icon}
                hasIcon={hasIcon}
                name={name}
                disabled={disabled}
                label={field?.label}
                hint={field?.hint}
                value={field?.value}
                placeholder={field?.placeholder}
              />
            )}
            {field?.kind === 'textarea' && (
              <Textarea
                className="FormControlsSection__data-textarea"
                name={name}
                label={field?.label}
                value={field?.value}
                placeholder={field?.placeholder}
                rows={field?.rows}
              />
            )}
            {field?.kind === 'select' && (
              <FormSelect
                className="FormControlsSection__data-select"
                label={field?.label}
                value={field?.value}
              />
            )}
            {field?.kind === 'toggle' && (
              <FormToggle
                className="FormControlsSection__data-toggle"
                label={field?.label}
                value={field?.value}
              />
            )}
          </div>
        ))}
      </section>
    </main>
  );
}
