/**
 * Generated by @facadeur/codegen-react from the "form-controls-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { FormControlsSection } from './component';
export type { FormControlsSectionProps } from './types';
