/**
 * Generated by @facadeur/codegen-react from the "form-controls-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export interface FormControlsSectionProps {
  formFields?: {
    id: string;
    kind: 'input' | 'textarea' | 'select' | 'toggle';
    label: string;
    value?: string;
    placeholder?: string;
    hint?: string;
    rows?: number;
  }[];
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
