/**
 * Generated by @facadeur/codegen-react from the "product-card" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { ProductCardProps } from './types';
import { Button } from '../Button';

export function ProductCard({
  variant = 'default',
  title,
  price,
  imageSrc,
  imageAlt,
  buttonLabel,
  className,
}: ProductCardProps) {
  return variant === 'compact' ? (
    <article
      data-component="product-card"
      data-variant={variant}
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <img src={imageSrc} alt={imageAlt} className={styles['image']} />
      <div className={styles['content']}>
        <h2 className={styles['title']}>{title}</h2>
        <p className={styles['price']}>{price}</p>
        <Button className="ProductCard__button" label={buttonLabel} />
      </div>
    </article>
  ) : (
    <article
      data-component="product-card"
      data-variant={variant}
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <img src={imageSrc} alt={imageAlt} className={styles['image']} />
      <div className={styles['content']}>
        <h2 className={styles['title']}>{title}</h2>
        <p className={styles['price']}>{price}</p>
        <Button className="ProductCard__button" label={buttonLabel} />
      </div>
    </article>
  );
}
