/**
 * Generated by @facadeur/codegen-react from the "product-card" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { ProductCardProps } from './types';
import { Button } from '../Button';

export function ProductCard({
  variant = 'default',
  title,
  price,
  imageSrc,
  imageAlt,
  buttonLabel,
  nodeId,
  className,
}: ProductCardProps) {
  return variant === 'compact' ? (
    <article
      data-component="product-card"
      data-node={nodeId}
      data-variant={variant}
      className={[styles.f_root_95igqt, className].filter(Boolean).join(' ')}
    >
      <img data-node="image" src={imageSrc} alt={imageAlt} className={styles.f_image_1dr5e62} />
      <div data-node="content" className={styles.f_content_145thoi}>
        <h2 data-node="title" className={styles.f_title_16a95ah}>
          {title}
        </h2>
        <p data-node="price" className={styles.f_price_34jfhm}>
          {price}
        </p>
        <Button nodeId="button" className={styles.f_button_is7gq9} label={buttonLabel} />
      </div>
    </article>
  ) : (
    <article
      data-component="product-card"
      data-node={nodeId}
      data-variant={variant}
      className={[styles.f_root_95igqt, className].filter(Boolean).join(' ')}
    >
      <img data-node="image" src={imageSrc} alt={imageAlt} className={styles.f_image_1dr5e62} />
      <div data-node="content" className={styles.f_content_145thoi}>
        <h2 data-node="title" className={styles.f_title_16a95ah}>
          {title}
        </h2>
        <p data-node="price" className={styles.f_price_34jfhm}>
          {price}
        </p>
        <Button nodeId="button" className={styles.f_button_is7gq9} label={buttonLabel} />
      </div>
    </article>
  );
}
