/**
 * Generated by @facadeur/codegen-react from the "product-card" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { ProductCard } from './component';
export type { ProductCardProps, ProductCardVariant } from './types';
