/**
 * Generated by @facadeur/codegen-react from the "product-card" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type ProductCardVariant = 'default' | 'compact';

export interface ProductCardProps {
  variant?: ProductCardVariant;
  title?: string;
  price?: string;
  imageSrc?: string;
  imageAlt?: string;
  buttonLabel?: string;
  label?: string;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
