/**
 * Generated by @facadeur/codegen-react from the "product-card" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export type ProductCardVariant = 'default' | 'compact';

export interface ProductCardData {
  title?: string;
  price?: string;
  imageSrc?: string;
  imageAlt?: string;
  buttonLabel?: string;
  label?: string;
}

export interface ProductCardProps extends ComponentProps, ProductCardData {
  variant?: ProductCardVariant;
}
