import type { Node } from '@facadeur/domain';
import { tokenIds as exampleTokenIds } from '../catalog/tokens/idList';
import { ids as exampleFormControlsSectionIds } from './idList';
import { tokenRef } from '../references';

export const styles = {
  [exampleFormControlsSectionIds.nodes.p1]: {
    width: 'auto',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.text.secondary),
    font: tokenRef(exampleTokenIds.type.caption),
    fontWeight: '600',
    letterSpacing: '0.12em',
    margin: tokenRef(exampleTokenIds.space.scale.step0),
    textTransform: 'uppercase',
  },
  [exampleFormControlsSectionIds.nodes.h11]: {
    width: 'auto',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.text.primary),
    font: tokenRef(exampleTokenIds.type.title),
    margin: tokenRef(exampleTokenIds.space.scale.step0),
  },
  [exampleFormControlsSectionIds.nodes.p2]: {
    width: '100%',
    height: 'auto',
    maxWidth: '680px',
    color: tokenRef(exampleTokenIds.color.text.secondary),
    font: tokenRef(exampleTokenIds.type.body),
  },
  [exampleFormControlsSectionIds.nodes.header1]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: tokenRef(exampleTokenIds.space.scale.step4),
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.h21]: {
    width: 'auto',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.text.primary),
    font: tokenRef(exampleTokenIds.type.heading),
    margin: tokenRef(exampleTokenIds.space.scale.step0),
  },
  [exampleFormControlsSectionIds.nodes.div2]: {
    width: '250px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div3]: {
    width: '250px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div1]: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: tokenRef(exampleTokenIds.space.gap.md),
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.section1]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.gap.md),
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.h22]: {
    width: 'auto',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.text.primary),
    font: tokenRef(exampleTokenIds.type.heading),
    margin: tokenRef(exampleTokenIds.space.scale.step0),
  },
  [exampleFormControlsSectionIds.nodes.div5]: {
    width: '250px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div6]: {
    width: '250px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div7]: {
    width: '250px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div8]: {
    width: '250px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div4]: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: tokenRef(exampleTokenIds.space.gap.md),
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.section2]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.gap.md),
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.h23]: {
    width: 'auto',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.text.primary),
    font: tokenRef(exampleTokenIds.type.heading),
    margin: tokenRef(exampleTokenIds.space.scale.step0),
  },
  [exampleFormControlsSectionIds.nodes.div10]: {
    width: '250px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div11]: {
    width: '250px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div12]: {
    width: '250px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div13]: {
    width: '270px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div14]: {
    width: '180px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div15]: {
    width: '180px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div16]: {
    width: '180px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div9]: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: tokenRef(exampleTokenIds.space.gap.lg),
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.section3]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.gap.md),
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.h24]: {
    width: 'auto',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.text.primary),
    font: tokenRef(exampleTokenIds.type.heading),
    margin: tokenRef(exampleTokenIds.space.scale.step0),
  },
  [exampleFormControlsSectionIds.nodes.p3]: {
    width: '100%',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.text.secondary),
    font: tokenRef(exampleTokenIds.type.caption),
    margin: tokenRef(exampleTokenIds.space.scale.step0),
  },
  [exampleFormControlsSectionIds.nodes.span1]: {
    width: '150px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.span2]: {
    width: '100px',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.span3]: {
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div18]: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokenRef(exampleTokenIds.space.scale.step3),
    padding: tokenRef(exampleTokenIds.space.scale.step2),
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div17]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.scale.step0),
    width: '100%',
    height: 'auto',
    border: '1px solid ' + tokenRef(exampleTokenIds.color.border.default),
    borderRadius: '{shape.radius}',
  },
  [exampleFormControlsSectionIds.nodes.div22]: {
    width: 'auto',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.section4]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.gap.md),
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.h25]: {
    width: 'auto',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.div23]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.gap.md),
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.section5]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.gap.md),
    width: '100%',
    height: 'auto',
  },
  [exampleFormControlsSectionIds.nodes.root]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.scale.step8),
    padding: tokenRef(exampleTokenIds.space.scale.step8),
    width: '100%',
    height: 'auto',
  },
} satisfies Readonly<Record<string, NonNullable<Node['style']>>>;
