/**
 * Generated by @facadeur/codegen-react from the "form-input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

'use client';

import styles from './style.module.css';
import type { FormInputProps } from './types';

export function FormInput({
  value,
  placeholder,
  name,
  disabled,
  onCommit,
  nodeId,
  className,
}: FormInputProps) {
  return (
    <input
      data-component="form-input"
      data-node={nodeId}
      type="text"
      autoComplete="off"
      value={value}
      placeholder={placeholder}
      name={name}
      disabled={disabled}
      onChange={(event) => onCommit?.({ value: event.currentTarget.value })}
      className={[styles['root'], className].filter(Boolean).join(' ')}
    />
  );
}
