/**
 * Generated by @facadeur/codegen-react from the "form-input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { FormInput } from './component';
export type { FormInputProps } from './types';
