/**
 * Generated by @facadeur/codegen-react from the "form-input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export interface FormInputData {
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
}

export interface FormInputProps extends ComponentProps, FormInputData {
  onCommit?: (payload: { value: string }) => void;
}
