/** Generated by @facadeur/codegen-react from the schema catalog. Do not edit by hand. */

export type CardSchema = {
  eyebrow?: string;
  title?: string;
  body?: string;
  [key: string]: unknown;
};
