/** Generated by @facadeur/codegen-react from the schema catalog. Do not edit by hand. */
export type { InputSchema } from './InputSchema';
export type { TextareaSchema } from './TextareaSchema';
export type { ImageSchema } from './ImageSchema';
export type { VideoSchema } from './VideoSchema';
export type { CardSchema } from './CardSchema';
export type { MediaSchema } from './MediaSchema';
