/** Generated by @facadeur/codegen-react from the schema catalog. Do not edit by hand. */

export type InputSchema = {
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
  [key: string]: unknown;
};
