/** Generated by @facadeur/codegen-react from the schema catalog. Do not edit by hand. */
import type { ImageSchema } from './ImageSchema';
import type { VideoSchema } from './VideoSchema';
export type MediaSchema = {
  kind: 'image' | 'video';
  src: string;
  alt?: string;
  poster?: string;
  ratio?: string;
  [key: string]: unknown;
} & (ImageSchema | VideoSchema);
