/** Generated by @facadeur/codegen-react from the schema catalog. Do not edit by hand. */

export type TextareaSchema = {
  label?: string;
  value?: string;
  placeholder?: string;
  name?: string;
  rows?: number;
  [key: string]: unknown;
};
