import type { Node } from '@facadeur/domain';
import { tokenIds as exampleTokenIds } from '../catalog/tokens/idList';
import { ids as exampleSpecimenSectionIds } from './idList';
import { tokenRef } from '../references';

export const styles = {
  [exampleSpecimenSectionIds.nodes.p1]: {
    width: 'auto',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.accent.default),
    font: tokenRef(exampleTokenIds.type.caption),
    letterSpacing: '0.18em',
    margin: tokenRef(exampleTokenIds.space.scale.step0),
    textTransform: 'uppercase',
  },
  [exampleSpecimenSectionIds.nodes.h11]: {
    width: 'auto',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.text.primary),
    font: tokenRef(exampleTokenIds.type.display),
    margin: tokenRef(exampleTokenIds.space.scale.step0),
  },
  [exampleSpecimenSectionIds.nodes.p2]: {
    width: '100%',
    height: 'auto',
    maxWidth: '640px',
    color: tokenRef(exampleTokenIds.color.text.secondary),
    font: tokenRef(exampleTokenIds.type.body),
    margin: tokenRef(exampleTokenIds.space.scale.step0),
  },
  [exampleSpecimenSectionIds.nodes.div1]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.stack.md),
    width: '100%',
    height: 'auto',
  },
  [exampleSpecimenSectionIds.nodes.p3]: {
    width: 'auto',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.text.secondary),
    font: tokenRef(exampleTokenIds.type.caption),
    letterSpacing: '0.16em',
    margin: tokenRef(exampleTokenIds.space.scale.step0),
    textTransform: 'uppercase',
  },
  [exampleSpecimenSectionIds.nodes.div3]: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: tokenRef(exampleTokenIds.space.gap.sm),
    width: '100%',
    height: 'auto',
  },
  [exampleSpecimenSectionIds.nodes.div2]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.stack.sm),
    width: '100%',
    height: 'auto',
  },
  [exampleSpecimenSectionIds.nodes.p4]: {
    width: 'auto',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.text.secondary),
    font: tokenRef(exampleTokenIds.type.caption),
    letterSpacing: '0.16em',
    margin: tokenRef(exampleTokenIds.space.scale.step0),
    textTransform: 'uppercase',
  },
  [exampleSpecimenSectionIds.nodes.div10]: {
    width: '300px',
    height: 'auto',
  },
  [exampleSpecimenSectionIds.nodes.div11]: {
    width: '300px',
    height: 'auto',
  },
  [exampleSpecimenSectionIds.nodes.div9]: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: tokenRef(exampleTokenIds.space.gap.md),
    width: '100%',
    height: 'auto',
  },
  [exampleSpecimenSectionIds.nodes.div8]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.stack.sm),
    width: '100%',
    height: 'auto',
  },
  [exampleSpecimenSectionIds.nodes.p5]: {
    width: 'auto',
    height: 'auto',
    color: tokenRef(exampleTokenIds.color.text.secondary),
    font: tokenRef(exampleTokenIds.type.caption),
    letterSpacing: '0.16em',
    margin: tokenRef(exampleTokenIds.space.scale.step0),
    textTransform: 'uppercase',
  },
  [exampleSpecimenSectionIds.nodes.div14]: {
    width: '100%',
    height: 'auto',
  },
  [exampleSpecimenSectionIds.nodes.div15]: {
    height: 'auto',
    width: 'auto',
  },
  [exampleSpecimenSectionIds.nodes.div13]: {
    display: 'grid',
    flexDirection: 'column',
    alignItems: 'end',
    justifyContent: 'stretch',
    gap: tokenRef(exampleTokenIds.space.gap.lg),
    height: 'auto',
    alignContent: 'stretch',
    gridTemplateColumns: 'repeat(1, minmax(0, 1fr))',
    justifyItems: 'stretch',
    rowGap: tokenRef(exampleTokenIds.radius.lg),
  },
  [exampleSpecimenSectionIds.nodes.div12]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.stack.sm),
    width: '100%',
    height: 'auto',
  },
  [exampleSpecimenSectionIds.nodes.root]: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: tokenRef(exampleTokenIds.space.stack.lg),
    padding: tokenRef(exampleTokenIds.space.inset.lg),
    width: '100%',
    height: 'auto',
  },
} satisfies Readonly<Record<string, NonNullable<Node['style']>>>;
