/**
 * Generated by @facadeur/codegen-react from the "media" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { MediaProps } from './types';

export function Media({ kind = 'image', src, alt, ratio, nodeId, className }: MediaProps) {
  return (
    <div
      data-component="media"
      data-node={nodeId}
      className={[styles.f_root_95igqt, className].filter(Boolean).join(' ')}
    >
      {kind === 'image' && (
        <img
          data-node="image"
          src={src}
          alt={alt}
          className={styles.f_image_1dr5e62}
          style={{ aspectRatio: ratio }}
        />
      )}
      {kind === 'video' && (
        <video
          data-node="video"
          controls
          src={src}
          className={styles.f_video_1lfe6i4}
          style={{ aspectRatio: ratio }}
        />
      )}
    </div>
  );
}
