/**
 * Generated by @facadeur/codegen-react from the "media" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { MediaProps } from './types';

export function Media({ kind = 'image', src, alt, poster, ratio, className }: MediaProps) {
  return (
    <div data-component="media" className={[styles['root'], className].filter(Boolean).join(' ')}>
      {kind === 'image' && (
        <img src={src} alt={alt} className={styles['image']} style={{ aspectRatio: ratio }} />
      )}
      {kind === 'video' && (
        <video
          controls
          src={src}
          poster={poster}
          className={styles['video']}
          style={{ aspectRatio: ratio }}
        />
      )}
    </div>
  );
}
