/**
 * Generated by @facadeur/codegen-react from the "media" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { Media } from './component';
export type { MediaProps, MediaData } from './types';
