/**
 * Generated by @facadeur/codegen-react from the "media" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export interface MediaProps {
  kind?: 'image' | 'video';
  src: string;
  alt?: string;
  ratio?: string;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
