/**
 * Generated by @facadeur/codegen-react from the "media" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export interface MediaData {
  kind?: 'image' | 'video';
  src: string;
  alt?: string;
  poster?: string;
  ratio?: string;
}

export interface MediaProps extends ComponentProps, MediaData {}
