/**
 * Generated by @facadeur/codegen-react from the "editor-field-row" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type EditorFieldRowState = 'default' | 'selected';

export interface EditorFieldRowProps {
  name?: string;
  type?: string;
  value?: string;
  state?: EditorFieldRowState;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function EditorFieldRow({
  name = 'label',
  type = 'text',
  value = 'Button',
  state = 'default',
  nodeId,
  className,
}: EditorFieldRowProps) {
  return (
    <div
      data-component="editor-field-row"
      data-node={nodeId}
      data-variant-state={state}
      className={className}
    >
      <span data-node="name">{name}</span>
      <span data-node="type">{type}</span>
      <span data-node="value">{value}</span>
    </div>
  );
}
