/**
 * Generated by @facadeur/codegen-react from the "editor-text-input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type EditorTextInputState = 'default' | 'focused' | 'disabled' | 'invalid';

export interface EditorTextInputProps {
  label?: string;
  value?: string;
  placeholder?: string;
  hint?: string;
  state?: EditorTextInputState;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function EditorTextInput({
  label = 'Label',
  value = 'Value',
  placeholder = 'Placeholder',
  hint = 'Optional hint',
  state = 'default',
  nodeId,
  className,
}: EditorTextInputProps) {
  return (
    <label
      data-component="editor-text-input"
      data-node={nodeId}
      data-variant-state={state}
      className={className}
    >
      <span data-node="label">{label}</span>
      <input
        data-node="control"
        type="text"
        readOnly
        tabIndex={-1}
        value={value}
        placeholder={placeholder}
      />
      <span data-node="hint">{hint}</span>
    </label>
  );
}
