/**
 * Generated by @facadeur/codegen-react from the "editor-toggle" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type EditorToggleState = 'on' | 'off' | 'disabled';

export interface EditorToggleProps {
  label?: string;
  state?: EditorToggleState;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function EditorToggle({
  label = 'Enabled',
  state = 'on',
  nodeId,
  className,
}: EditorToggleProps) {
  return (
    <label
      data-component="editor-toggle"
      data-node={nodeId}
      data-variant-state={state}
      className={className}
    >
      <span data-node="label">{label}</span>
      <div data-node="switch">
        <span data-node="state">On</span>
      </div>
    </label>
  );
}
