/**
 * Generated by @facadeur/codegen-react from the "editor-controls" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import { EditorControlsSection } from './EditorControlsSection';

export interface EditorControlsProps {
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function EditorControls({ nodeId, className }: EditorControlsProps) {
  return (
    <div data-component="editor-controls" data-node={nodeId} className={className}>
      <EditorControlsSection nodeId="editor-controls-section" />
    </div>
  );
}
