/**
 * Generated by @facadeur/codegen-react from the "editor-segmented" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type EditorSegmentedState = 'start' | 'center' | 'end';

export interface EditorSegmentedProps {
  label?: string;
  state?: EditorSegmentedState;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function EditorSegmented({
  label = 'Alignment',
  state = 'start',
  nodeId,
  className,
}: EditorSegmentedProps) {
  return (
    <div
      data-component="editor-segmented"
      data-node={nodeId}
      data-variant-state={state}
      className={className}
    >
      <span data-node="label">{label}</span>
      <div data-node="options">
        <span data-node="start">Start</span>
        <span data-node="center">Center</span>
        <span data-node="end">End</span>
      </div>
    </div>
  );
}
