/**
 * Generated by @facadeur/codegen-react from the "form-select" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type FormSelectState = 'default' | 'focused' | 'disabled';

export interface FormSelectProps {
  label?: string;
  value?: string;
  state?: FormSelectState;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function FormSelect({
  label = 'Property',
  value = 'Choose value',
  state = 'default',
  nodeId,
  className,
}: FormSelectProps) {
  return (
    <label
      data-component="form-select"
      data-node={nodeId}
      data-variant-state={state}
      className={className}
    >
      <span data-node="label">{label}</span>
      <div data-node="control">
        <span data-node="value">{value}</span>
        <img
          data-node="chevron"
          aria-hidden="true"
          src="data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 16 16%22%3E%3Cpath d=%22m4 6 4 4 4-4%22 fill=%22none%22 stroke=%22%236f675e%22 stroke-width=%221.5%22 stroke-linecap=%22round%22 stroke-linejoin=%22round%22/%3E%3C/svg%3E"
          alt=""
        />
      </div>
    </label>
  );
}
