/**
 * Generated by @facadeur/codegen-react from the "form-toggle" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type FormToggleState = 'on' | 'off' | 'disabled';

export interface FormToggleProps {
  label?: string;
  state?: FormToggleState;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function FormToggle({
  label = 'Enabled',
  state = 'on',
  nodeId,
  className,
}: FormToggleProps) {
  return (
    <label
      data-component="form-toggle"
      data-node={nodeId}
      data-variant-state={state}
      className={className}
    >
      <span data-node="label">{label}</span>
      <div data-node="switch">
        <span data-node="state">On</span>
      </div>
    </label>
  );
}
