/**
 * Generated by @facadeur/codegen-react from the "form-text-input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type FormTextInputState = 'default' | 'focused' | 'disabled' | 'invalid';

export interface FormTextInputProps {
  label?: string;
  value?: string;
  placeholder?: string;
  hint?: string;
  icon?: string;
  hasIcon?: boolean;
  state?: FormTextInputState;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function FormTextInput({
  label = 'Label',
  value = 'Value',
  placeholder = 'Placeholder',
  hint = 'Optional hint',
  icon,
  hasIcon = false,
  state = 'default',
  nodeId,
  className,
}: FormTextInputProps) {
  return (
    <label
      data-component="form-text-input"
      data-node={nodeId}
      data-variant-state={state}
      className={className}
    >
      <span data-node="label">{label}</span>
      <div data-node="controlShell">
        <img
          data-node="leadingIcon"
          aria-hidden="true"
          src={icon}
          alt=""
          hidden={hasIcon === false}
        />
        <input
          data-node="control"
          type="text"
          readOnly
          tabIndex={-1}
          value={value}
          placeholder={placeholder}
        />
      </div>
      <span data-node="hint">{hint}</span>
    </label>
  );
}
