/**
 * Generated by @facadeur/codegen-react from the "form-controls" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import { FormControlsSection } from './FormControlsSection';

export interface FormControlsProps {
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function FormControls({ nodeId, className }: FormControlsProps) {
  return (
    <div data-component="form-controls" data-node={nodeId} className={className}>
      <FormControlsSection nodeId="form-controls-section" />
    </div>
  );
}
