/**
 * Generated by @facadeur/codegen-react from the "form-input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export interface FormInputProps {
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
  onCommit?: (payload: { value: string }) => void;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function FormInput({
  value,
  placeholder,
  name,
  disabled,
  onCommit,
  nodeId,
  className,
}: FormInputProps) {
  return (
    <input
      data-component="form-input"
      data-node={nodeId}
      type="text"
      autoComplete="off"
      value={value}
      placeholder={placeholder}
      name={name}
      disabled={disabled}
      onChange={(event) => onCommit?.({ value: event.currentTarget.value })}
      className={className}
    />
  );
}
