/**
 * Generated by @facadeur/codegen-react from the "form-text-input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import { FormInput } from './FormInput';

export type FormTextInputState = 'default' | 'focused' | 'disabled' | 'invalid';

export interface FormTextInputProps {
  label?: string;
  hint?: string;
  icon?: string;
  hasIcon?: boolean;
  value?: string;
  placeholder?: string;
  state?: FormTextInputState;
  onCommit?: (payload: { value: string }) => void;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function FormTextInput({
  label,
  hint,
  icon,
  hasIcon,
  value,
  placeholder,
  state = 'default',
  onCommit,
  nodeId,
  className,
}: FormTextInputProps) {
  return (
    <label
      data-component="form-text-input"
      data-node={nodeId}
      data-variant-state={state}
      className={className}
    >
      <span data-node="label">{label}</span>
      <div data-node="controlShell">
        <img
          data-node="leadingIcon"
          aria-hidden="true"
          src={icon}
          alt=""
          hidden={hasIcon === false}
        />
        <FormInput nodeId="control" value={value} placeholder={placeholder} onCommit={onCommit} />
      </div>
      <span data-node="hint">{hint}</span>
    </label>
  );
}
