/**
 * Generated by @facadeur/codegen-react from the "input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export interface InputProps {
  label?: string;
  value?: string;
  placeholder?: string;
  name?: string;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function Input({
  label = 'Label',
  value = '',
  placeholder = '',
  name = '',
  nodeId,
  className,
}: InputProps) {
  return (
    <label data-component="input" data-node={nodeId} className={className}>
      <span data-node="label">{label}</span>
      <input
        data-node="control"
        type="text"
        readOnly
        tabIndex={-1}
        autoComplete="off"
        value={value}
        placeholder={placeholder}
        name={name}
      />
    </label>
  );
}
