/**
 * Generated by @facadeur/codegen-react from the "media" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export interface MediaProps {
  kind?: 'image' | 'video';
  src: string;
  alt?: string;
  ratio?: string;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function Media({ kind = 'image', src, alt, ratio, nodeId, className }: MediaProps) {
  return (
    <div data-component="media" data-node={nodeId} className={className}>
      {kind === 'image' && (
        <img data-node="image" src={src} alt={alt} style={{ aspectRatio: ratio }} />
      )}
      {kind === 'video' && (
        <video data-node="video" controls src={src} style={{ aspectRatio: ratio }} />
      )}
    </div>
  );
}
