/**
 * Generated by @facadeur/codegen-react from the "product-card" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import { Button } from './Button';

export type ProductCardVariant = 'default' | 'compact';

export interface ProductCardProps {
  variant?: ProductCardVariant;
  title?: string;
  price?: string;
  imageSrc?: string;
  imageAlt?: string;
  buttonLabel?: string;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function ProductCard({
  variant = 'default',
  title,
  price,
  imageSrc,
  imageAlt,
  buttonLabel,
  nodeId,
  className,
}: ProductCardProps) {
  return variant === 'compact' ? (
    <article
      data-component="product-card"
      data-node={nodeId}
      data-variant={variant}
      className={className}
    >
      <img data-node="image" src={imageSrc} alt={imageAlt} />
      <div data-node="content">
        <h2 data-node="title">{title}</h2>
        <p data-node="price">{price}</p>
        <Button nodeId="button" label={buttonLabel} />
      </div>
    </article>
  ) : (
    <article
      data-component="product-card"
      data-node={nodeId}
      data-variant={variant}
      className={className}
    >
      <img data-node="image" src={imageSrc} alt={imageAlt} />
      <div data-node="content">
        <h2 data-node="title">{title}</h2>
        <p data-node="price">{price}</p>
        <Button nodeId="button" label={buttonLabel} />
      </div>
    </article>
  );
}
