/**
 * Generated by @facadeur/codegen-react from the "specimen-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import { Button } from './Button';
import { Card } from './Card';
import { Input } from './Input';
import { SignIn } from './SignIn';

export interface SpecimenSectionProps {
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function SpecimenSection({ nodeId, className }: SpecimenSectionProps) {
  return (
    <div data-component="specimen-section" data-node={nodeId} className={className}>
      <div data-node="intro">
        <p data-node="kicker">facadeur</p>
        <h1 data-node="heading">Specimen</h1>
        <p data-node="lede">
          Auto layout, token styles, and a sign-in card that overrides the input border for its
          children.
        </p>
      </div>
      <div data-node="buttons">
        <p data-node="label-button">Button</p>
        <div data-node="button-row">
          <Button nodeId="btn-primary" label="Primary" tone="primary" size="md" />
          <Button nodeId="btn-secondary" label="Secondary" tone="secondary" size="md" />
          <Button nodeId="btn-ghost" label="Ghost" tone="ghost" size="md" />
          <Button nodeId="btn-small" label="Small" tone="primary" size="sm" />
        </div>
      </div>
      <div data-node="fields">
        <p data-node="label-input">Input</p>
        <div data-node="input-row">
          <Input nodeId="input-email" label="Email" value="ada@atelier.test" name="email" />
          <Input nodeId="input-search" label="Search" placeholder="Search components" name="q" />
        </div>
      </div>
      <div data-node="cards">
        <p data-node="label-card">Card</p>
        <div data-node="card-row">
          <Card
            nodeId="card-notes"
            eyebrow="Layout"
            title="Field notes"
            body="Props fill the template. Click the title, or click the card padding to select the card itself."
          />
          <SignIn nodeId="card-signin" />
        </div>
      </div>
    </div>
  );
}
