/**
 * Generated by @facadeur/codegen-react from the "specimen-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import { Button } from './Button';
import { Card } from './Card';
import { Input } from './Input';
import { SignIn } from './SignIn';

export interface SpecimenSectionProps {
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
  childFields?: Record<string, Record<string, unknown>>;
}

export function SpecimenSection({ nodeId, className, childFields }: SpecimenSectionProps) {
  return (
    <div data-component="specimen-section" data-node={nodeId} className={className}>
      <div data-node="intro">
        <p data-node="kicker">facadeur</p>
        <h1 data-node="heading">Specimen</h1>
        <p data-node="lede">
          Auto layout, token styles, and a sign-in card that overrides the input border for its
          children.
        </p>
      </div>
      <div data-node="buttons">
        <p data-node="label-button">Button</p>
        <div data-node="button-row">
          <Button
            nodeId="btn-primary"
            label={
              childFields?.['btn-primary']?.label !== undefined
                ? (childFields?.['btn-primary']?.label as string)
                : 'Primary'
            }
            tone="primary"
            size="md"
          />
          <Button
            nodeId="btn-secondary"
            label={
              childFields?.['btn-secondary']?.label !== undefined
                ? (childFields?.['btn-secondary']?.label as string)
                : 'Secondary'
            }
            tone="secondary"
            size="md"
          />
          <Button
            nodeId="btn-ghost"
            label={
              childFields?.['btn-ghost']?.label !== undefined
                ? (childFields?.['btn-ghost']?.label as string)
                : 'Ghost'
            }
            tone="ghost"
            size="md"
          />
          <Button
            nodeId="btn-small"
            label={
              childFields?.['btn-small']?.label !== undefined
                ? (childFields?.['btn-small']?.label as string)
                : 'Small'
            }
            tone="primary"
            size="sm"
          />
        </div>
      </div>
      <div data-node="fields">
        <p data-node="label-input">Input</p>
        <div data-node="input-row">
          <Input
            nodeId="input-email"
            label={
              childFields?.['input-email']?.label !== undefined
                ? (childFields?.['input-email']?.label as string)
                : 'Email'
            }
            name={
              childFields?.['input-email']?.name !== undefined
                ? (childFields?.['input-email']?.name as string)
                : 'email'
            }
            value={
              childFields?.['input-email']?.value !== undefined
                ? (childFields?.['input-email']?.value as string)
                : 'ada@atelier.test'
            }
            placeholder={
              childFields?.['input-email']?.placeholder !== undefined
                ? (childFields?.['input-email']?.placeholder as string)
                : undefined
            }
          />
          <Input
            nodeId="input-search"
            label={
              childFields?.['input-search']?.label !== undefined
                ? (childFields?.['input-search']?.label as string)
                : 'Search'
            }
            name={
              childFields?.['input-search']?.name !== undefined
                ? (childFields?.['input-search']?.name as string)
                : 'q'
            }
            placeholder={
              childFields?.['input-search']?.placeholder !== undefined
                ? (childFields?.['input-search']?.placeholder as string)
                : 'Search components'
            }
            value={
              childFields?.['input-search']?.value !== undefined
                ? (childFields?.['input-search']?.value as string)
                : undefined
            }
          />
        </div>
      </div>
      <div data-node="cards">
        <p data-node="label-card">Card</p>
        <div data-node="card-row">
          <Card
            nodeId="card-notes"
            body={
              childFields?.['card-notes']?.body !== undefined
                ? (childFields?.['card-notes']?.body as string)
                : 'Props fill the template. Click the title, or click the card padding to select the card itself.'
            }
            eyebrow={
              childFields?.['card-notes']?.eyebrow !== undefined
                ? (childFields?.['card-notes']?.eyebrow as string)
                : 'Layout'
            }
            title={
              childFields?.['card-notes']?.title !== undefined
                ? (childFields?.['card-notes']?.title as string)
                : 'Field notes'
            }
          />
          <SignIn
            nodeId="card-signin"
            eyebrow={
              childFields?.['card-signin']?.eyebrow !== undefined
                ? (childFields?.['card-signin']?.eyebrow as string)
                : undefined
            }
            title={
              childFields?.['card-signin']?.title !== undefined
                ? (childFields?.['card-signin']?.title as string)
                : undefined
            }
            body={
              childFields?.['card-signin']?.body !== undefined
                ? (childFields?.['card-signin']?.body as string)
                : undefined
            }
          />
        </div>
      </div>
    </div>
  );
}
