/**
 * Generated by @facadeur/codegen-react from the "textarea" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type TextareaResize = 'vertical' | 'none';

export interface TextareaProps {
  label?: string;
  value?: string;
  placeholder?: string;
  name?: string;
  rows?: number;
  resize?: TextareaResize;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}

export function Textarea({
  label = 'Label',
  value = '',
  placeholder = '',
  name = '',
  rows = 4,
  resize = 'vertical',
  nodeId,
  className,
}: TextareaProps) {
  return (
    <label
      data-component="textarea"
      data-node={nodeId}
      data-variant-resize={resize}
      className={className}
    >
      <span data-node="label">{label}</span>
      <textarea
        data-node="control"
        readOnly
        tabIndex={-1}
        placeholder={placeholder}
        name={name}
        rows={rows}
      >
        {value}
      </textarea>
    </label>
  );
}
