import type { DesignTokenRecord, DesignTokenUuid } from '@facadeur/domain';
import { tokenIds as exampleTokenIds } from './idList';
import { tokenRef } from '../../references';

export const colors = {
  [exampleTokenIds.color.accent.default]: {
    uuid: exampleTokenIds.color.accent.default,
    label: 'Default',
    group: 'accent',
    valueType: 'color',
    value: tokenRef(exampleTokenIds.color.blue._500),
  },
  [exampleTokenIds.color.accent.hover]: {
    uuid: exampleTokenIds.color.accent.hover,
    label: 'Hover',
    group: 'accent',
    valueType: 'color',
    value: tokenRef(exampleTokenIds.color.blue._600),
  },
  [exampleTokenIds.color.bg.canvas]: {
    uuid: exampleTokenIds.color.bg.canvas,
    label: 'Canvas',
    group: 'bg',
    valueType: 'color',
    value: tokenRef(exampleTokenIds.color.neutral._0),
  },
  [exampleTokenIds.color.bg.inverse]: {
    uuid: exampleTokenIds.color.bg.inverse,
    label: 'Inverse',
    group: 'bg',
    valueType: 'color',
    value: tokenRef(exampleTokenIds.color.neutral._900),
  },
  [exampleTokenIds.color.bg.muted]: {
    uuid: exampleTokenIds.color.bg.muted,
    label: 'Muted',
    group: 'bg',
    valueType: 'color',
    value: tokenRef(exampleTokenIds.color.neutral._50),
  },
  [exampleTokenIds.color.blue._500]: {
    uuid: exampleTokenIds.color.blue._500,
    label: '500',
    group: 'blue',
    valueType: 'color',
    value: '#2563eb',
  },
  [exampleTokenIds.color.blue._600]: {
    uuid: exampleTokenIds.color.blue._600,
    label: '600',
    group: 'blue',
    valueType: 'color',
    value: '#1d4ed8',
  },
  [exampleTokenIds.color.border.default]: {
    uuid: exampleTokenIds.color.border.default,
    label: 'Default',
    group: 'border',
    valueType: 'color',
    value: tokenRef(exampleTokenIds.color.neutral._200),
  },
  [exampleTokenIds.color.danger.default]: {
    uuid: exampleTokenIds.color.danger.default,
    label: 'Default',
    group: 'danger',
    valueType: 'color',
    value: tokenRef(exampleTokenIds.color.red._500),
  },
  [exampleTokenIds.color.green._600]: {
    uuid: exampleTokenIds.color.green._600,
    label: '600',
    group: 'green',
    valueType: 'color',
    value: '#16a34a',
  },
  [exampleTokenIds.color.neutral._0]: {
    uuid: exampleTokenIds.color.neutral._0,
    label: '0',
    group: 'neutral',
    valueType: 'color',
    value: '#ffffff',
  },
  [exampleTokenIds.color.neutral._50]: {
    uuid: exampleTokenIds.color.neutral._50,
    label: '50',
    group: 'neutral',
    valueType: 'color',
    value: '#f8fafc',
  },
  [exampleTokenIds.color.neutral._100]: {
    uuid: exampleTokenIds.color.neutral._100,
    label: '100',
    group: 'neutral',
    valueType: 'color',
    value: '#f1f5f9',
  },
  [exampleTokenIds.color.neutral._200]: {
    uuid: exampleTokenIds.color.neutral._200,
    label: '200',
    group: 'neutral',
    valueType: 'color',
    value: '#e2e8f0',
  },
  [exampleTokenIds.color.neutral._400]: {
    uuid: exampleTokenIds.color.neutral._400,
    label: '400',
    group: 'neutral',
    valueType: 'color',
    value: '#94a3b8',
  },
  [exampleTokenIds.color.neutral._600]: {
    uuid: exampleTokenIds.color.neutral._600,
    label: '600',
    group: 'neutral',
    valueType: 'color',
    value: '#475569',
  },
  [exampleTokenIds.color.neutral._900]: {
    uuid: exampleTokenIds.color.neutral._900,
    label: '900',
    group: 'neutral',
    valueType: 'color',
    value: '#0f172a',
  },
  [exampleTokenIds.color.red._500]: {
    uuid: exampleTokenIds.color.red._500,
    label: '500',
    group: 'red',
    valueType: 'color',
    value: '#dc2626',
  },
  [exampleTokenIds.color.success.default]: {
    uuid: exampleTokenIds.color.success.default,
    label: 'Default',
    group: 'success',
    valueType: 'color',
    value: tokenRef(exampleTokenIds.color.green._600),
  },
  [exampleTokenIds.color.text.inverse]: {
    uuid: exampleTokenIds.color.text.inverse,
    label: 'Inverse',
    group: 'text',
    valueType: 'color',
    value: tokenRef(exampleTokenIds.color.neutral._0),
  },
  [exampleTokenIds.color.text.primary]: {
    uuid: exampleTokenIds.color.text.primary,
    label: 'Primary',
    group: 'text',
    valueType: 'color',
    value: tokenRef(exampleTokenIds.color.neutral._900),
  },
  [exampleTokenIds.color.text.secondary]: {
    uuid: exampleTokenIds.color.text.secondary,
    label: 'Secondary',
    group: 'text',
    valueType: 'color',
    value: tokenRef(exampleTokenIds.color.neutral._600),
  },
} as const satisfies Readonly<Record<DesignTokenUuid, DesignTokenRecord>>;
