import type { DesignTokenRecord, DesignTokenUuid, Uuid } from '@facadeur/domain';
import { tokenIds as exampleTokenIds } from './idList';
import { tokenRef } from '../../references';

export const spacing = {
  [exampleTokenIds.space.scale.step0]: {
    uuid: exampleTokenIds.space.scale.step0,
    label: '0',
    group: '',
    valueType: 'dimension',
    value: '0',
  },
  [exampleTokenIds.space.scale.step1]: {
    uuid: exampleTokenIds.space.scale.step1,
    label: '1',
    group: '',
    valueType: 'dimension',
    value: '4px',
  },
  [exampleTokenIds.space.scale.step2]: {
    uuid: exampleTokenIds.space.scale.step2,
    label: '2',
    group: '',
    valueType: 'dimension',
    value: '8px',
  },
  [exampleTokenIds.space.scale.step3]: {
    uuid: exampleTokenIds.space.scale.step3,
    label: '3',
    group: '',
    valueType: 'dimension',
    value: '12px',
  },
  [exampleTokenIds.space.scale.step4]: {
    uuid: exampleTokenIds.space.scale.step4,
    label: '4',
    group: '',
    valueType: 'dimension',
    value: '16px',
  },
  [exampleTokenIds.space.scale.step5]: {
    uuid: exampleTokenIds.space.scale.step5,
    label: '5',
    group: '',
    valueType: 'dimension',
    value: '20px',
  },
  [exampleTokenIds.space.scale.step6]: {
    uuid: exampleTokenIds.space.scale.step6,
    label: '6',
    group: '',
    valueType: 'dimension',
    value: '24px',
  },
  [exampleTokenIds.space.scale.step8]: {
    uuid: exampleTokenIds.space.scale.step8,
    label: '8',
    group: '',
    valueType: 'dimension',
    value: '32px',
  },
  [exampleTokenIds.space.scale.step10]: {
    uuid: exampleTokenIds.space.scale.step10,
    label: '10',
    group: '',
    valueType: 'dimension',
    value: '40px',
  },
  [exampleTokenIds.space.scale.step12]: {
    uuid: exampleTokenIds.space.scale.step12,
    label: '12',
    group: '',
    valueType: 'dimension',
    value: '48px',
  },
  [exampleTokenIds.space.scale.step16]: {
    uuid: exampleTokenIds.space.scale.step16,
    label: '16',
    group: '',
    valueType: 'dimension',
    value: '64px',
  },
  [exampleTokenIds.space.scale.step20]: {
    uuid: exampleTokenIds.space.scale.step20,
    label: '20',
    group: '',
    valueType: 'dimension',
    value: '80px',
  },
  [exampleTokenIds.space.scale.step24]: {
    uuid: exampleTokenIds.space.scale.step24,
    label: '24',
    group: '',
    valueType: 'dimension',
    value: '96px',
  },
  [exampleTokenIds.space.gap.lg]: {
    uuid: exampleTokenIds.space.gap.lg,
    label: 'Lg',
    group: 'gap',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step6),
  },
  [exampleTokenIds.space.gap.md]: {
    uuid: exampleTokenIds.space.gap.md,
    label: 'Md',
    group: 'gap',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step4),
  },
  [exampleTokenIds.space.gap.sm]: {
    uuid: exampleTokenIds.space.gap.sm,
    label: 'Sm',
    group: 'gap',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step2),
  },
  [exampleTokenIds.space.gap.xs]: {
    uuid: exampleTokenIds.space.gap.xs,
    label: 'Xs',
    group: 'gap',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step1),
  },
  [exampleTokenIds.space.inset.lg]: {
    uuid: exampleTokenIds.space.inset.lg,
    label: 'Lg',
    group: 'inset',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step6),
  },
  [exampleTokenIds.space.inset.md]: {
    uuid: exampleTokenIds.space.inset.md,
    label: 'Md',
    group: 'inset',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step4),
  },
  [exampleTokenIds.space.inset.sm]: {
    uuid: exampleTokenIds.space.inset.sm,
    label: 'Sm',
    group: 'inset',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step3),
  },
  [exampleTokenIds.space.inset.xs]: {
    uuid: exampleTokenIds.space.inset.xs,
    label: 'Xs',
    group: 'inset',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step2),
  },
  [exampleTokenIds.space.stack.lg]: {
    uuid: exampleTokenIds.space.stack.lg,
    label: 'Lg',
    group: 'stack',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step8),
  },
  [exampleTokenIds.space.stack.md]: {
    uuid: exampleTokenIds.space.stack.md,
    label: 'Md',
    group: 'stack',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step4),
  },
  [exampleTokenIds.space.stack.sm]: {
    uuid: exampleTokenIds.space.stack.sm,
    label: 'Sm',
    group: 'stack',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step2),
  },
  [exampleTokenIds.space.stack.xs]: {
    uuid: exampleTokenIds.space.stack.xs,
    label: 'Xs',
    group: 'stack',
    valueType: 'dimension',
    value: tokenRef(exampleTokenIds.space.scale.step1),
  },
} as const satisfies Readonly<Record<DesignTokenUuid, DesignTokenRecord>>;
