/**
 * Generated by @facadeur/codegen-react from the "card" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import './style.css';
import type { CardProps } from './types';

export function Card({ eyebrow, title, body, nodeId, className }: CardProps) {
  return (
    <article data-component="card" data-node={nodeId} className={className}>
      <p data-node="eyebrow">{eyebrow}</p>
      <h2 data-node="title">{title}</h2>
      <p data-node="body">{body}</p>
    </article>
  );
}
