/**
 * Generated by @facadeur/codegen-react from the "card" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { CardProps } from './types';

export function Card({ eyebrow, title, body, className }: CardProps) {
  return (
    <article
      data-component="card"
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <p className={styles['eyebrow']}>{eyebrow}</p>
      <h2 className={styles['title']}>{title}</h2>
      <p className={styles['body']}>{body}</p>
    </article>
  );
}
