/**
 * Generated by @facadeur/codegen-react from the "card" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { Card } from './component';
export type { CardProps, CardData } from './types';
