/**
 * Generated by @facadeur/codegen-react from the "card" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export interface CardData {
  eyebrow?: string;
  title?: string;
  body?: string;
}

export interface CardProps extends ComponentProps, CardData {}
