/**
 * Generated by @facadeur/codegen-react from the "specimen-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { SpecimenSectionProps } from './types';
import { Button } from '../Button';
import { Card } from '../Card';
import { Input } from '../Input';
import { SignIn } from '../SignIn';

export function SpecimenSection({ nodeId, className, childFields }: SpecimenSectionProps) {
  return (
    <div
      data-component="specimen-section"
      data-node={nodeId}
      className={[styles.f_root_95igqt, className].filter(Boolean).join(' ')}
    >
      <div data-node="intro" className={styles.f_intro_ctvstt}>
        <p data-node="kicker" className={styles.f_kicker_n8l4j8}>
          facadeur
        </p>
        <h1 data-node="heading" className={styles.f_heading_1870pat}>
          Specimen
        </h1>
        <p data-node="lede" className={styles.f_lede_6gu931}>
          Auto layout, token styles, and a sign-in card that overrides the input border for its
          children.
        </p>
      </div>
      <div data-node="buttons" className={styles.f_buttons_151kopy}>
        <p data-node="label-button" className={styles.f_label_button_1djee4k}>
          Button
        </p>
        <div data-node="button-row" className={styles.f_button_row_apzzv4}>
          <Button
            nodeId="btn-primary"
            className={styles.f_btn_primary_clrl40}
            label={
              childFields?.['btn-primary']?.label !== undefined
                ? (childFields?.['btn-primary']?.label as string)
                : 'Primary'
            }
            tone="primary"
            size="md"
          />
          <Button
            nodeId="btn-secondary"
            className={styles.f_btn_secondary_1jfsi8}
            label={
              childFields?.['btn-secondary']?.label !== undefined
                ? (childFields?.['btn-secondary']?.label as string)
                : 'Secondary'
            }
            tone="secondary"
            size="md"
          />
          <Button
            nodeId="btn-ghost"
            className={styles.f_btn_ghost_ptaa5x}
            label={
              childFields?.['btn-ghost']?.label !== undefined
                ? (childFields?.['btn-ghost']?.label as string)
                : 'Ghost'
            }
            tone="ghost"
            size="md"
          />
          <Button
            nodeId="btn-small"
            className={styles.f_btn_small_1b8dm5}
            label={
              childFields?.['btn-small']?.label !== undefined
                ? (childFields?.['btn-small']?.label as string)
                : 'Small'
            }
            tone="primary"
            size="sm"
          />
        </div>
      </div>
      <div data-node="fields" className={styles.f_fields_1qg0os}>
        <p data-node="label-input" className={styles.f_label_input_1kyjsk4}>
          Input
        </p>
        <div data-node="input-row" className={styles.f_input_row_8msj2m}>
          <Input
            nodeId="input-email"
            className={styles.f_input_email_1b58xa}
            label={
              childFields?.['input-email']?.label !== undefined
                ? (childFields?.['input-email']?.label as string)
                : 'Email'
            }
            name={
              childFields?.['input-email']?.name !== undefined
                ? (childFields?.['input-email']?.name as string)
                : 'email'
            }
            value={
              childFields?.['input-email']?.value !== undefined
                ? (childFields?.['input-email']?.value as string)
                : 'ada@atelier.test'
            }
            placeholder={
              childFields?.['input-email']?.placeholder !== undefined
                ? (childFields?.['input-email']?.placeholder as string)
                : undefined
            }
          />
          <Input
            nodeId="input-search"
            className={styles.f_input_search_h4lpai}
            label={
              childFields?.['input-search']?.label !== undefined
                ? (childFields?.['input-search']?.label as string)
                : 'Search'
            }
            name={
              childFields?.['input-search']?.name !== undefined
                ? (childFields?.['input-search']?.name as string)
                : 'q'
            }
            placeholder={
              childFields?.['input-search']?.placeholder !== undefined
                ? (childFields?.['input-search']?.placeholder as string)
                : 'Search components'
            }
            value={
              childFields?.['input-search']?.value !== undefined
                ? (childFields?.['input-search']?.value as string)
                : undefined
            }
          />
        </div>
      </div>
      <div data-node="cards" className={styles.f_cards_101yo90}>
        <p data-node="label-card" className={styles.f_label_card_fq8fri}>
          Card
        </p>
        <div data-node="card-row" className={styles.f_card_row_1w04xey}>
          <Card
            nodeId="card-notes"
            className={styles.f_card_notes_1rwl3zn}
            body={
              childFields?.['card-notes']?.body !== undefined
                ? (childFields?.['card-notes']?.body as string)
                : 'Props fill the template. Click the title, or click the card padding to select the card itself.'
            }
            eyebrow={
              childFields?.['card-notes']?.eyebrow !== undefined
                ? (childFields?.['card-notes']?.eyebrow as string)
                : 'Layout'
            }
            title={
              childFields?.['card-notes']?.title !== undefined
                ? (childFields?.['card-notes']?.title as string)
                : 'Field notes'
            }
          />
          <SignIn
            nodeId="card-signin"
            className={styles.f_card_signin_qspryo}
            eyebrow={
              childFields?.['card-signin']?.eyebrow !== undefined
                ? (childFields?.['card-signin']?.eyebrow as string)
                : undefined
            }
            title={
              childFields?.['card-signin']?.title !== undefined
                ? (childFields?.['card-signin']?.title as string)
                : undefined
            }
            body={
              childFields?.['card-signin']?.body !== undefined
                ? (childFields?.['card-signin']?.body as string)
                : undefined
            }
          />
        </div>
      </div>
    </div>
  );
}
