/**
 * Generated by @facadeur/codegen-react from the "specimen-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { SpecimenSectionProps } from './types';
import { Button } from '../Button';
import { Card } from '../Card';
import { Input } from '../Input';
import { SignIn } from '../SignIn';

export function SpecimenSection({
  eyebrow,
  title,
  body,
  value,
  placeholder,
  name,
  disabled,
  label,
  className,
  childFields,
}: SpecimenSectionProps) {
  return (
    <div
      data-component="specimen-section"
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <div className={styles['intro']}>
        <p className={styles['kicker']}>facadeur</p>
        <h1 className={styles['heading']}>Specimen</h1>
        <p className={styles['lede']}>
          Auto layout, token styles, and a sign-in card that overrides the input border for its
          children.
        </p>
      </div>
      <div className={styles['buttons']}>
        <p className={styles['label-button']}>Button</p>
        <div className={styles['button-row']}>
          <Button
            className="SpecimenSection__btn-primary"
            label={
              childFields?.['btn-primary']?.label !== undefined
                ? (childFields?.['btn-primary']?.label as string)
                : 'Primary'
            }
            tone="primary"
            size="md"
          />
          <Button
            className="SpecimenSection__btn-secondary"
            label={
              childFields?.['btn-secondary']?.label !== undefined
                ? (childFields?.['btn-secondary']?.label as string)
                : 'Secondary'
            }
            tone="secondary"
            size="md"
          />
          <Button
            className="SpecimenSection__btn-ghost"
            label={
              childFields?.['btn-ghost']?.label !== undefined
                ? (childFields?.['btn-ghost']?.label as string)
                : 'Ghost'
            }
            tone="ghost"
            size="md"
          />
          <Button
            className="SpecimenSection__btn-small"
            label={
              childFields?.['btn-small']?.label !== undefined
                ? (childFields?.['btn-small']?.label as string)
                : 'Small'
            }
            tone="primary"
            size="sm"
          />
        </div>
      </div>
      <div className={styles['fields']}>
        <p className={styles['label-input']}>Input</p>
        <div className={styles['input-row']}>
          <Input
            className="SpecimenSection__input-email"
            placeholder={
              childFields?.['input-email']?.placeholder !== undefined
                ? (childFields?.['input-email']?.placeholder as string)
                : placeholder
            }
            disabled={
              childFields?.['input-email']?.disabled !== undefined
                ? (childFields?.['input-email']?.disabled as boolean)
                : disabled
            }
            label={
              childFields?.['input-email']?.label !== undefined
                ? (childFields?.['input-email']?.label as string)
                : 'Email'
            }
            name={
              childFields?.['input-email']?.name !== undefined
                ? (childFields?.['input-email']?.name as string)
                : 'email'
            }
            value={
              childFields?.['input-email']?.value !== undefined
                ? (childFields?.['input-email']?.value as string)
                : 'ada@atelier.test'
            }
          />
          <Input
            className="SpecimenSection__input-search"
            value={
              childFields?.['input-search']?.value !== undefined
                ? (childFields?.['input-search']?.value as string)
                : value
            }
            disabled={
              childFields?.['input-search']?.disabled !== undefined
                ? (childFields?.['input-search']?.disabled as boolean)
                : disabled
            }
            label={
              childFields?.['input-search']?.label !== undefined
                ? (childFields?.['input-search']?.label as string)
                : 'Search'
            }
            name={
              childFields?.['input-search']?.name !== undefined
                ? (childFields?.['input-search']?.name as string)
                : 'q'
            }
            placeholder={
              childFields?.['input-search']?.placeholder !== undefined
                ? (childFields?.['input-search']?.placeholder as string)
                : 'Search components'
            }
          />
        </div>
      </div>
      <div className={styles['cards']}>
        <p className={styles['label-card']}>Card</p>
        <div className={styles['card-row']}>
          <Card
            className="SpecimenSection__card-notes"
            body={
              childFields?.['card-notes']?.body !== undefined
                ? (childFields?.['card-notes']?.body as string)
                : 'Props fill the template. Click the title, or click the card padding to select the card itself.'
            }
            eyebrow={
              childFields?.['card-notes']?.eyebrow !== undefined
                ? (childFields?.['card-notes']?.eyebrow as string)
                : 'Layout'
            }
            title={
              childFields?.['card-notes']?.title !== undefined
                ? (childFields?.['card-notes']?.title as string)
                : 'Field notes'
            }
          />
          <SignIn
            className="SpecimenSection__card-signin"
            eyebrow={
              childFields?.['card-signin']?.eyebrow !== undefined
                ? (childFields?.['card-signin']?.eyebrow as string)
                : eyebrow
            }
            title={
              childFields?.['card-signin']?.title !== undefined
                ? (childFields?.['card-signin']?.title as string)
                : title
            }
            body={
              childFields?.['card-signin']?.body !== undefined
                ? (childFields?.['card-signin']?.body as string)
                : body
            }
            value={
              childFields?.['card-signin']?.value !== undefined
                ? (childFields?.['card-signin']?.value as string)
                : value
            }
            placeholder={
              childFields?.['card-signin']?.placeholder !== undefined
                ? (childFields?.['card-signin']?.placeholder as string)
                : placeholder
            }
            name={
              childFields?.['card-signin']?.name !== undefined
                ? (childFields?.['card-signin']?.name as string)
                : name
            }
            disabled={
              childFields?.['card-signin']?.disabled !== undefined
                ? (childFields?.['card-signin']?.disabled as boolean)
                : disabled
            }
            label={
              childFields?.['card-signin']?.label !== undefined
                ? (childFields?.['card-signin']?.label as string)
                : label
            }
          />
        </div>
      </div>
    </div>
  );
}
