/**
 * Generated by @facadeur/codegen-react from the "specimen-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { SpecimenSection } from './component';
export type { SpecimenSectionProps, SpecimenSectionData } from './types';
