/**
 * Generated by @facadeur/codegen-react from the "specimen-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export interface SpecimenSectionProps {
  eyebrow?: string;
  title?: string;
  body?: string;
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
  label?: string;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
  childFields?: Record<string, Record<string, unknown>>;
}
