/**
 * Generated by @facadeur/codegen-react from the "specimen-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export interface SpecimenSectionData {
  eyebrow?: string;
  title?: string;
  body?: string;
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
  label?: string;
}

export interface SpecimenSectionProps extends ComponentProps, SpecimenSectionData {
  childFields?: Record<string, Record<string, unknown>>;
}
