/**
 * Generated by @facadeur/codegen-react from the "form-text-input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { FormTextInput } from './component';
export type { FormTextInputProps, FormTextInputState } from './types';
