/**
 * Generated by @facadeur/codegen-react from the "form-text-input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export type FormTextInputState = 'default' | 'focused' | 'disabled' | 'invalid';

export interface FormTextInputData {
  label?: string;
  hint?: string;
  icon?: string;
  hasIcon?: boolean;
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
}

export interface FormTextInputProps extends ComponentProps, FormTextInputData {
  state?: FormTextInputState;
  onCommit?: (payload: { value: string }) => void;
}
