/**
 * Generated by @facadeur/codegen-react from the "form-text-input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type FormTextInputState = 'default' | 'focused' | 'disabled' | 'invalid';

export interface FormTextInputProps {
  label?: string;
  hint?: string;
  icon?: string;
  hasIcon?: boolean;
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
  state?: FormTextInputState;
  onCommit?: (payload: { value: string }) => void;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
