/**
 * Generated by @facadeur/codegen-react from the "form-toggle" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { FormToggleProps } from './types';

export function FormToggle({ label, value, state = 'on', className }: FormToggleProps) {
  return (
    <label
      data-component="form-toggle"
      data-variant-state={state}
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <span className={styles['label']}>{label}</span>
      <div className={styles['control']}>
        <div className={styles['switch']}>
          <span className={styles['thumb']} />
        </div>
        <span className={styles['state']}>{value}</span>
      </div>
    </label>
  );
}
