/**
 * Generated by @facadeur/codegen-react from the "form-toggle" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import './style.css';
import type { FormToggleProps } from './types';

export function FormToggle({ label, value, state = 'on', nodeId, className }: FormToggleProps) {
  return (
    <label
      data-component="form-toggle"
      data-node={nodeId}
      data-variant-state={state}
      className={className}
    >
      <span data-node="label">{label}</span>
      <div data-node="control">
        <div data-node="switch">
          <span data-node="thumb" />
        </div>
        <span data-node="state">{value}</span>
      </div>
    </label>
  );
}
