/**
 * Generated by @facadeur/codegen-react from the "form-toggle" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { FormToggle } from './component';
export type { FormToggleProps, FormToggleData, FormToggleState } from './types';
