/**
 * Generated by @facadeur/codegen-react from the "form-toggle" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export type FormToggleState = 'on' | 'off' | 'disabled';

export interface FormToggleData {
  label?: string;
  value?: string;
}

export interface FormToggleProps extends ComponentProps, FormToggleData {
  state?: FormToggleState;
}
