/**
 * Generated by @facadeur/codegen-react from the "sign-in" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { SignInProps } from './types';
import { Button } from '../Button';
import { Input } from '../Input';

export function SignIn({
  eyebrow,
  title,
  body,
  placeholder,
  disabled,
  nodeId,
  className,
}: SignInProps) {
  return (
    <article
      data-component="sign-in"
      data-node={nodeId}
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <p data-node="eyebrow" className={styles['eyebrow']}>
        {eyebrow}
      </p>
      <h2 data-node="title" className={styles['title']}>
        {title}
      </h2>
      <p data-node="body" className={styles['body']}>
        {body}
      </p>
      <Input
        nodeId="email"
        className={styles['email']}
        placeholder={placeholder}
        disabled={disabled}
        label="Work email"
        value="ada@atelier.test"
        name="work-email"
      />
      <Button
        nodeId="continue"
        className={styles['continue']}
        label="Continue"
        tone="primary"
        size="sm"
      />
    </article>
  );
}
