/**
 * Generated by @facadeur/codegen-react from the "sign-in" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { SignInProps } from './types';
import { Button } from '../Button';
import { Input } from '../Input';

export function SignIn({ eyebrow, title, body, nodeId, className }: SignInProps) {
  return (
    <article
      data-component="sign-in"
      data-node={nodeId}
      className={[styles.f_root_95igqt, className].filter(Boolean).join(' ')}
    >
      <p data-node="eyebrow" className={styles.f_eyebrow_95073g}>
        {eyebrow}
      </p>
      <h2 data-node="title" className={styles.f_title_16a95ah}>
        {title}
      </h2>
      <p data-node="body" className={styles.f_body_1oy6jcl}>
        {body}
      </p>
      <Input
        nodeId="email"
        className={styles.f_email_12fq213}
        label="Work email"
        value="ada@atelier.test"
        name="work-email"
      />
      <Button
        nodeId="continue"
        className={styles.f_continue_1d8gyf8}
        label="Continue"
        tone="primary"
        size="sm"
      />
    </article>
  );
}
