/**
 * Generated by @facadeur/codegen-react from the "sign-in" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { SignInProps } from './types';
import { Button } from '../Button';
import { Input } from '../Input';

export function SignIn({ eyebrow, title, body, placeholder, disabled, className }: SignInProps) {
  return (
    <article
      data-component="sign-in"
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <p className={styles['eyebrow']}>{eyebrow}</p>
      <h2 className={styles['title']}>{title}</h2>
      <p className={styles['body']}>{body}</p>
      <Input
        className="SignIn__email"
        placeholder={placeholder}
        disabled={disabled}
        label="Work email"
        value="ada@atelier.test"
        name="work-email"
      />
      <Button className="SignIn__continue" label="Continue" tone="primary" size="sm" />
    </article>
  );
}
