/**
 * Generated by @facadeur/codegen-react from the "sign-in" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export interface SignInData {
  eyebrow?: string;
  title?: string;
  body?: string;
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
  label?: string;
}

export interface SignInProps extends ComponentProps, SignInData {}
