/**
 * Generated by @facadeur/codegen-react from the "sign-in" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export interface SignInProps {
  eyebrow?: string;
  title?: string;
  body?: string;
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
  label?: string;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
