/**
 * Generated by @facadeur/codegen-react from the "new-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import { Fragment } from 'react';
import type { NewSectionProps } from './types';
import { Card } from '../Card';
import { Textarea } from '../Textarea';

export function NewSection({ items, className }: NewSectionProps) {
  return (
    <div
      data-component="new-section"
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <Fragment>
        {(items ?? []).map((item, itemIndex) => (
          <Fragment key={itemIndex}>
            {(() => {
              switch (item.type) {
                case 'card':
                  return <Card {...item.props} className="NewSection__Card" />;
                case 'textarea':
                  return <Textarea {...item.props} className="NewSection__Textarea" />;
                default:
                  return null;
              }
            })()}
          </Fragment>
        ))}
      </Fragment>
    </div>
  );
}
