/**
 * Generated by @facadeur/codegen-react from the "new-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { NewSection } from './component';
export type { NewSectionProps, NewSectionData } from './types';
