/**
 * Generated by @facadeur/codegen-react from the "new-section" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

import type { CardData } from '../Card/types';
import type { TextareaData } from '../Textarea/types';

export interface CardItem {
  type: 'card';
  props: CardData;
}
export interface TextareaItem {
  type: 'textarea';
  props: TextareaData;
}
export interface NewSectionData {
  items: (CardItem | TextareaItem)[];
}

export interface NewSectionProps extends ComponentProps, NewSectionData {}
