/**
 * Generated by @facadeur/codegen-react from the "textarea" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { TextareaProps } from './types';

export function Textarea({
  label,
  value,
  placeholder,
  name,
  rows,
  resize = 'vertical',
  nodeId,
  className,
}: TextareaProps) {
  return (
    <label
      data-component="textarea"
      data-node={nodeId}
      data-variant-resize={resize}
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <span data-node="label" className={styles['label']}>
        {label}
      </span>
      <textarea
        data-node="control"
        readOnly
        tabIndex={-1}
        placeholder={placeholder}
        name={name}
        rows={rows}
        className={styles['control']}
      >
        {value}
      </textarea>
    </label>
  );
}
