/**
 * Generated by @facadeur/codegen-react from the "textarea" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { Textarea } from './component';
export type { TextareaProps, TextareaData, TextareaResize } from './types';
