/**
 * Generated by @facadeur/codegen-react from the "textarea" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type TextareaResize = 'vertical' | 'none';

export interface TextareaProps {
  label?: string;
  value?: string;
  placeholder?: string;
  name?: string;
  rows?: number;
  resize?: TextareaResize;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
