/**
 * Generated by @facadeur/codegen-react from the "textarea" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

import type { TextareaSchema } from '../../types/TextareaSchema';

export type TextareaResize = 'vertical' | 'none';

export type TextareaData = Pick<
  TextareaSchema,
  'label' | 'value' | 'placeholder' | 'name' | 'rows'
>;

export interface TextareaProps extends ComponentProps, TextareaData {
  resize?: TextareaResize;
}
