/**
 * Generated by @facadeur/codegen-react from the "input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

'use client';

import styles from './style.module.css';
import type { InputProps } from './types';
import { FormInput } from '../FormInput';

export function Input({
  label,
  value,
  placeholder,
  name,
  onCommit,
  nodeId,
  className,
}: InputProps) {
  return (
    <label
      data-component="input"
      data-node={nodeId}
      className={[styles.f_root_95igqt, className].filter(Boolean).join(' ')}
    >
      <span data-node="label" className={styles.f_label_1wf4cn1}>
        {label}
      </span>
      <FormInput
        nodeId="control"
        className={styles.f_control_mx9w2m}
        value={value}
        placeholder={placeholder}
        name={name}
        onCommit={onCommit}
      />
    </label>
  );
}
