/**
 * Generated by @facadeur/codegen-react from the "input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

'use client';

import styles from './style.module.css';
import type { InputProps } from './types';
import { FormInput } from '../FormInput';

export function Input({ label, value, placeholder, name, onCommit, className }: InputProps) {
  return (
    <label data-component="input" className={[styles['root'], className].filter(Boolean).join(' ')}>
      <span className={styles['label']}>{label}</span>
      <FormInput
        className="Input__control"
        value={value}
        placeholder={placeholder}
        name={name}
        onCommit={onCommit}
        disabled={false}
      />
    </label>
  );
}
