/**
 * Generated by @facadeur/codegen-react from the "input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

'use client';

import './style.css';
import type { InputProps } from './types';
import { FormInput } from '../FormInput';

export function Input({
  label,
  value,
  placeholder,
  name,
  onCommit,
  nodeId,
  className,
}: InputProps) {
  return (
    <label data-component="input" data-node={nodeId} className={className}>
      <span data-node="label">{label}</span>
      <FormInput
        nodeId="control"
        value={value}
        placeholder={placeholder}
        name={name}
        onCommit={onCommit}
      />
    </label>
  );
}
