/**
 * Generated by @facadeur/codegen-react from the "input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { Input } from './component';
export type { InputProps, InputData } from './types';
