/**
 * Generated by @facadeur/codegen-react from the "input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export interface InputData {
  label?: string;
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
}

export interface InputProps extends ComponentProps, InputData {
  onCommit?: (payload: { value: string }) => void;
}
