/**
 * Generated by @facadeur/codegen-react from the "input" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export interface InputProps {
  label?: string;
  value?: string;
  placeholder?: string;
  name?: string;
  onCommit?: (payload: { value: string }) => void;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
