import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { describe, expect, it } from 'vitest';
import { writeGeneratedFiles } from '../src/generated-output.js';

const banner = '/** Generated by @facadeur/codegen-react. */\n';

describe('generated output ownership', () => {
  it('migrates legacy generated files and preserves foreign files', () => {
    const root = mkdtempSync(join(tmpdir(), 'facadeur-output-'));
    try {
      mkdirSync(join(root, 'components'), { recursive: true });
      writeFileSync(join(root, 'components', 'Legacy.tsx'), `${banner}export {};\n`);
      writeFileSync(join(root, 'components', 'notes.md'), 'Keep me\n');

      writeGeneratedFiles(
        root,
        [{ path: 'components/Button/component.tsx', contents: `${banner}export {};\n` }],
        ['components'],
      );

      expect(existsSync(join(root, 'components', 'Legacy.tsx'))).toBe(false);
      expect(readFileSync(join(root, 'components', 'notes.md'), 'utf8')).toBe('Keep me\n');
      expect(
        JSON.parse(readFileSync(join(root, '.facadeur-codegen-manifest.json'), 'utf8')),
      ).toEqual({
        version: 1,
        files: ['components/Button/component.tsx'],
      });
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('removes only stale manifest-owned files on later runs', () => {
    const root = mkdtempSync(join(tmpdir(), 'facadeur-output-'));
    try {
      writeGeneratedFiles(
        root,
        [
          { path: 'components/Button/component.tsx', contents: `${banner}export {};\n` },
          { path: 'components/Card/component.tsx', contents: `${banner}export {};\n` },
        ],
        ['components'],
      );
      writeFileSync(join(root, 'components', 'Button', 'notes.md'), 'Keep me\n');

      writeGeneratedFiles(
        root,
        [{ path: 'components/Button/component.tsx', contents: `${banner}export {};\n` }],
        ['components'],
      );

      expect(existsSync(join(root, 'components', 'Card'))).toBe(false);
      expect(readFileSync(join(root, 'components', 'Button', 'notes.md'), 'utf8')).toBe(
        'Keep me\n',
      );
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('rejects generated paths outside the output root', () => {
    const root = mkdtempSync(join(tmpdir(), 'facadeur-output-'));
    try {
      expect(() =>
        writeGeneratedFiles(root, [{ path: '../escape.ts', contents: banner }], []),
      ).toThrow(/stay inside/);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
