/**
 * Generated by @facadeur/codegen-react from the "button" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { ButtonProps } from './types';

export function Button({ label, tone = 'primary', size = 'md', className }: ButtonProps) {
  return (
    <button
      data-component="button"
      data-variant-tone={tone}
      data-variant-size={size}
      type="button"
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      {label}
    </button>
  );
}
