/**
 * Generated by @facadeur/codegen-react from the "button" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import './style.css';
import type { ButtonProps } from './types';

export function Button({ label, tone = 'primary', size = 'md', nodeId, className }: ButtonProps) {
  return (
    <button
      data-component="button"
      data-node={nodeId}
      data-variant-tone={tone}
      data-variant-size={size}
      type="button"
      className={className}
    >
      {label}
    </button>
  );
}
