/**
 * Generated by @facadeur/codegen-react from the "button" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { Button } from './component';
export type { ButtonProps, ButtonData, ButtonTone, ButtonSize } from './types';
