/**
 * Generated by @facadeur/codegen-react from the "button" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type ButtonTone = 'primary' | 'secondary' | 'ghost';
export type ButtonSize = 'sm' | 'md';

export interface ButtonProps {
  label?: string;
  tone?: ButtonTone;
  size?: ButtonSize;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
