/**
 * Generated by @facadeur/codegen-react from the "button" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export type ButtonTone = 'primary' | 'secondary' | 'ghost';
export type ButtonSize = 'sm' | 'md';

export interface ButtonData {
  label?: string;
}

export interface ButtonProps extends ComponentProps, ButtonData {
  tone?: ButtonTone;
  size?: ButtonSize;
}
