/**
 * Generated by @facadeur/codegen-react from the "form-field-row" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { FormFieldRowProps } from './types';

export function FormFieldRow({
  name,
  type,
  value,
  state = 'default',
  className,
}: FormFieldRowProps) {
  return (
    <div
      data-component="form-field-row"
      data-variant-state={state}
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <span className={styles['name']}>{name}</span>
      <span className={styles['type']}>{type}</span>
      <span className={styles['value']}>{value}</span>
    </div>
  );
}
