/**
 * Generated by @facadeur/codegen-react from the "form-field-row" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import './style.css';
import type { FormFieldRowProps } from './types';

export function FormFieldRow({
  name,
  type,
  value,
  state = 'default',
  nodeId,
  className,
}: FormFieldRowProps) {
  return (
    <div
      data-component="form-field-row"
      data-node={nodeId}
      data-variant-state={state}
      className={className}
    >
      <span data-node="name">{name}</span>
      <span data-node="type">{type}</span>
      <span data-node="value">{value}</span>
    </div>
  );
}
