/**
 * Generated by @facadeur/codegen-react from the "form-field-row" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { FormFieldRowProps } from './types';

export function FormFieldRow({
  name,
  type,
  value,
  state = 'default',
  nodeId,
  className,
}: FormFieldRowProps) {
  return (
    <div
      data-component="form-field-row"
      data-node={nodeId}
      data-variant-state={state}
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <span data-node="name" className={styles['name']}>
        {name}
      </span>
      <span data-node="type" className={styles['type']}>
        {type}
      </span>
      <span data-node="value" className={styles['value']}>
        {value}
      </span>
    </div>
  );
}
