/**
 * Generated by @facadeur/codegen-react from the "form-field-row" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { FormFieldRow } from './component';
export type { FormFieldRowProps, FormFieldRowData, FormFieldRowState } from './types';
