/**
 * Generated by @facadeur/codegen-react from the "form-field-row" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type FormFieldRowState = 'default' | 'selected';

export interface FormFieldRowProps {
  name?: string;
  type?: string;
  value?: string;
  state?: FormFieldRowState;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
