/**
 * Generated by @facadeur/codegen-react from the "form-field-row" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export type FormFieldRowState = 'default' | 'selected';

export interface FormFieldRowData {
  name?: string;
  type?: string;
  value?: string;
}

export interface FormFieldRowProps extends ComponentProps, FormFieldRowData {
  state?: FormFieldRowState;
}
