/**
 * Generated by @facadeur/codegen-react from the "specimen" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import './style.css';
import type { SpecimenProps } from './types';
import { SpecimenSection } from '../SpecimenSection';

export function Specimen({ nodeId, className }: SpecimenProps) {
  return (
    <div data-component="specimen" data-node={nodeId} className={className}>
      <SpecimenSection
        nodeId="specimen-section"
        childFields={{ 'input-email': { value: 'ada@atelier.testyy' } }}
      />
    </div>
  );
}
