/**
 * Generated by @facadeur/codegen-react from the "specimen" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { SpecimenProps } from './types';
import { SpecimenSection } from '../SpecimenSection';

export function Specimen({
  eyebrow,
  title,
  body,
  value,
  placeholder,
  name,
  disabled,
  label,
  nodeId,
  className,
}: SpecimenProps) {
  return (
    <div
      data-component="specimen"
      data-node={nodeId}
      className={[styles['root'], className].filter(Boolean).join(' ')}
    >
      <SpecimenSection
        nodeId="specimen-section"
        className={styles['specimen-section']}
        eyebrow={eyebrow}
        title={title}
        body={body}
        value={value}
        placeholder={placeholder}
        name={name}
        disabled={disabled}
        label={label}
        childFields={{ 'input-email': { value: 'ada@atelier.testyy' } }}
      />
    </div>
  );
}
