/**
 * Generated by @facadeur/codegen-react from the "specimen" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { Specimen } from './component';
export type { SpecimenProps, SpecimenData } from './types';
