/**
 * Generated by @facadeur/codegen-react from the "specimen" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export interface SpecimenProps {
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
