/**
 * Generated by @facadeur/codegen-react from the "specimen" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export interface SpecimenData {
  eyebrow?: string;
  title?: string;
  body?: string;
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
  label?: string;
}

export interface SpecimenProps extends ComponentProps, SpecimenData {}
