import type { Breakpoint, DocumentFile } from '@facadeur/core';
import { compileDocument, type CompiledRule } from '@facadeur/style-engine';
import { renderDesignCss, type DesignInput } from '@facadeur/tokens';
import type { LocalClassNames } from './component/types.js';
import { instanceNodeIds } from './component/class-names.js';

const TOKEN_BANNER =
  '/* Generated by @facadeur/codegen-react. Tokens and fonts from the design document. */\n\n';

const COMPONENT_BANNER = `/* Generated by @facadeur/codegen-react.
 * CSS Modules classes are shared with the generated JSX. Token references stay var(--…).
 */

`;

/** Tokens and fonts as one stylesheet. Custom properties sit on `:root`. */
export function renderTokenCss(design?: DesignInput): string {
  const body = renderDesignCss(design ?? {});
  return `${TOKEN_BANNER}${body.endsWith('\n') ? body : `${body}\n`}`;
}

/** Render a document's rules using the same local class mapping as its JSX. */
export function renderDocumentCss(
  document: DocumentFile,
  classNames: LocalClassNames,
  breakpoints?: readonly Breakpoint[],
  catalog: readonly DocumentFile[] = [document],
): string {
  const rootClass = classNames.get(document.root.id);
  if (!rootClass) throw new Error(`Missing local CSS class for root of "${document.id}"`);
  const instances = instanceNodeIds(document);
  const compiled = compileDocument(document, {
    address: 'instance',
    ...(breakpoints?.length ? { breakpoints } : {}),
    catalog,
    selectorForNode: ({ node, nodeId, targetPath, defaultSelector }) => {
      const scope = `[data-component="${cssString(document.id)}"]`;
      if (!defaultSelector.startsWith(scope)) return defaultSelector;
      const moduleScope = `.${rootClass}`;
      const suffix = defaultSelector.slice(scope.length);
      if (targetPath) {
        return `${moduleScope}${suffix}`;
      }
      const className = classNames.get(nodeId);
      if (!className) return defaultSelector;
      if (nodeId === document.root.id) return `${moduleScope}${rootVariantAttributes(suffix)}`;
      if (node.type === 'instance' && document.styles?.children?.[node.id] !== undefined) {
        return `${moduleScope}${suffix}`;
      }
      return `${moduleScope}${rootVariantAttributes(suffix)} .${className}`;
    },
  });
  const base = compiled.filter((rule) => rule.minWidth === undefined);
  const widths = [
    ...new Set(compiled.flatMap((rule) => (rule.minWidth === undefined ? [] : [rule.minWidth]))),
  ].sort((left, right) => left - right);
  const chunks = [printRules(document, base, instances, 0)];
  for (const minWidth of widths) {
    const inner = printRules(
      document,
      compiled.filter((rule) => rule.minWidth === minWidth),
      instances,
      1,
    );
    if (!inner) continue;
    chunks.push(`@media (min-width: ${minWidth}px) {\n${inner}\n}`);
  }
  const selectors = new Set(
    compiled.flatMap((rule) => rule.selector.match(/\.([A-Za-z_][A-Za-z0-9_-]*)/g) ?? []),
  );
  const exportRules = [...classNames.values()]
    .filter((className) => !selectors.has(`.${className}`))
    .map((className) => `.${className} {}`);
  const body = [...chunks.filter(Boolean), ...exportRules].join('\n\n');
  const layerOrder = '@layer facadeur.components, facadeur.instances, facadeur.nested-instances;';
  return `${COMPONENT_BANNER}${layerOrder}${body ? `\n\n${body}` : ''}${body ? '\n' : ''}`;
}

function rootVariantAttributes(suffix: string): string {
  return [...suffix.matchAll(/\[data-variant(?:-[^=\]]+)?="(?:\\.|[^"])*"\]/g)]
    .map(([attribute]) => attribute)
    .join('');
}

function cssString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function printRules(
  document: DocumentFile,
  rules: readonly CompiledRule[],
  instances: ReadonlySet<string>,
  indent: number,
): string {
  const layers = [
    {
      name: 'facadeur.components',
      matches: (rule: CompiledRule) =>
        !rule.key.includes('/') && !isInstanceRule(rule, document, instances),
    },
    {
      name: 'facadeur.instances',
      matches: (rule: CompiledRule) =>
        !rule.key.includes('/') && isInstanceRule(rule, document, instances),
    },
    {
      name: 'facadeur.nested-instances',
      matches: (rule: CompiledRule) => rule.key.includes('/'),
    },
  ];
  const innerPad = '  '.repeat(indent);
  return layers
    .map(({ name, matches }) => {
      const body = rules
        .filter(matches)
        .map((rule) => printRule(rule, indent + 1))
        .filter(Boolean)
        .join('\n\n');
      return body ? `${innerPad}@layer ${name} {\n${body}\n${innerPad}}` : '';
    })
    .filter(Boolean)
    .join('\n\n');
}

function isInstanceRule(
  rule: CompiledRule,
  document: DocumentFile,
  instances: ReadonlySet<string>,
): boolean {
  const nodeId = rule.key.slice(document.id.length + 1).split(':', 1)[0];
  return nodeId !== undefined && instances.has(nodeId);
}

function printRule(rule: CompiledRule, indent: number): string {
  const pad = '  '.repeat(indent);
  const body = rule.declarations.map(([name, value]) => `${pad}  ${name}: ${value};`).join('\n');
  return `${pad}${rule.selector} {\n${body}\n${pad}}`;
}
