import type { Breakpoint, DocumentFile } from '@facadeur/core';
import { compileDocument, type CompiledRule } from '@facadeur/style-engine';
import { renderDesignCss, type DesignInput } from '@facadeur/tokens';

const TOKEN_BANNER =
  '/* Generated by @facadeur/codegen-react. Tokens and fonts from the design document. */\n\n';

const COMPONENT_BANNER = `/* Generated by @facadeur/codegen-react.
 * Style blocks compiled with address "instance". Token references stay var(--…).
 */

`;

/** Tokens and fonts as one stylesheet. Custom properties sit on `:root`. */
export function renderTokenCss(design?: DesignInput): string {
  const body = renderDesignCss(design ?? {});
  return `${TOKEN_BANNER}${body.endsWith('\n') ? body : `${body}\n`}`;
}

/**
 * Every document's style block and layout, in document order.
 * Base rules come first. Breakpoint overrides follow as `@media (min-width)`,
 * grouped by width, in the same order the compiler emitted them.
 */
export function renderComponentCss(
  documents: readonly DocumentFile[],
  breakpoints?: readonly Breakpoint[],
): string {
  const compiled = documents.flatMap((document) =>
    compileDocument(document, {
      address: 'instance',
      ...(breakpoints?.length ? { breakpoints } : {}),
    }),
  );
  const base = compiled.filter((rule) => rule.minWidth === undefined);
  const widths = [
    ...new Set(compiled.flatMap((rule) => (rule.minWidth === undefined ? [] : [rule.minWidth]))),
  ].sort((left, right) => left - right);
  const chunks = [printRules(base, 0)];
  for (const minWidth of widths) {
    const inner = printRules(
      compiled.filter((rule) => rule.minWidth === minWidth),
      1,
    );
    if (!inner) continue;
    chunks.push(`@media (min-width: ${minWidth}px) {\n${inner}\n}`);
  }
  const body = chunks.filter(Boolean).join('\n\n');
  return `${COMPONENT_BANNER}${body}${body ? '\n' : ''}`;
}

function printRules(rules: readonly CompiledRule[], indent: number): string {
  const pad = '  '.repeat(indent);
  return rules
    .map((rule) => {
      const body = rule.declarations
        .map(([name, value]) => `${pad}  ${name}: ${value};`)
        .join('\n');
      return `${pad}${rule.selector} {\n${body}\n${pad}}`;
    })
    .join('\n\n');
}
