import type { DocumentFile } from '@facadeur/core';
import type { DesignInput } from '@facadeur/tokens';
import { assignCatalog, renderComponent, type ComponentFile } from './component.js';
import { renderComponentCss, renderTokenCss } from './css.js';
import { CodegenError } from './names.js';

export interface GeneratedFile {
  path: string;
  contents: string;
}

export interface GenerateReactOptions {
  /** Atoms, components, sections, and pages. JSON documents, not a second model. */
  documents: readonly DocumentFile[];
  /** Tokens, fonts, and breakpoints. Usually the project template. */
  design?: DesignInput;
}

/** Turn facadeur documents into React components and the CSS they use. */
export function generateReact(options: GenerateReactOptions): GeneratedFile[] {
  const documents = [...options.documents].sort((left, right) =>
    left.id.localeCompare(right.id, 'en'),
  );
  const seen = new Set<string>();
  for (const document of documents) {
    if (seen.has(document.id)) {
      throw new CodegenError(`Duplicate document id "${document.id}"`);
    }
    seen.add(document.id);
  }
  const catalog = assignCatalog(documents);
  const components = documents.map((document) => renderComponent(document, catalog));
  const breakpoints = options.design?.breakpoints;
  return [
    { path: 'styles/tokens.css', contents: renderTokenCss(options.design) },
    {
      path: 'styles/components.css',
      contents: renderComponentCss(documents, breakpoints ? [...breakpoints] : undefined),
    },
    ...components.map(toFile),
    { path: 'index.ts', contents: renderIndex(components) },
  ];
}

export function designFromDocument(document: DocumentFile): DesignInput {
  return {
    ...(document.tokens ? { tokens: document.tokens } : {}),
    ...(document.fonts ? { fonts: document.fonts } : {}),
    ...(document.settings?.breakpoints ? { breakpoints: document.settings.breakpoints } : {}),
  };
}

function toFile(component: ComponentFile): GeneratedFile {
  return { path: component.path, contents: component.contents };
}

function renderIndex(components: readonly ComponentFile[]): string {
  const lines = [
    '/**',
    ' * Generated by @facadeur/codegen-react.',
    ' * The facadeur JSON is the source of truth. Do not edit by hand.',
    ' */',
    '',
  ];
  for (const component of components) {
    lines.push(`export { ${component.component} } from ${quotePath(component.path)};`);
    const types = [
      `${component.component}Props`,
      ...component.variantTypes.map((type) => type.name),
    ];
    lines.push(`export type { ${types.join(', ')} } from ${quotePath(component.path)};`);
  }
  lines.push('');
  return lines.join('\n');
}

function quotePath(file: string): string {
  const withoutExt = file.replace(/\.tsx$/, '');
  return `'./${withoutExt}'`;
}
