import type { DocumentFile } from '@facadeur/core';
import type { ComponentFile, PropSpec } from './component.js';

const kindTitles: Record<DocumentFile['kind'], string> = {
  atom: 'Atoms',
  component: 'Components',
  section: 'Sections',
  page: 'Pages',
};

export function generateStories(
  documents: readonly DocumentFile[],
  components: readonly ComponentFile[],
): { path: string; contents: string }[] {
  const byId = new Map(documents.map((document) => [document.id, document]));
  return components.map((component) => {
    const document = byId.get(component.id);
    if (!document) {
      throw new Error(`Missing document for component "${component.id}"`);
    }
    return {
      path: `src/stories/generated/${component.component}.stories.tsx`,
      contents: renderStory(document, component),
    };
  });
}

function renderStory(document: DocumentFile, file: ComponentFile): string {
  const title = `${kindTitles[document.kind]}/${file.component}`;
  const argLines = renderArgs(file.props);
  const lines = [
    '/**',
    ' * Generated by @facadeur/codegen-react.',
    ' * The facadeur JSON is the source of truth. Do not edit by hand.',
    ' */',
    '',
    "import type { Meta, StoryObj } from '@storybook/react';",
    `import { ${file.component} } from '@facadeur/ui';`,
    '',
    'const meta = {',
    `  title: ${quote(title)},`,
    `  component: ${file.component},`,
    "  tags: ['autodocs'],",
  ];
  if (argLines.length) {
    lines.push('  args: {');
    lines.push(...argLines);
    lines.push('  },');
  }
  lines.push(`} satisfies Meta<typeof ${file.component}>;`, '', 'export default meta;', '');
  lines.push(`type Story = StoryObj<typeof meta>;`, '', 'export const Default: Story = {};', '');
  return lines.join('\n');
}

function renderArgs(props: readonly PropSpec[]): string[] {
  const lines: string[] = [];
  for (const prop of props) {
    const value = prop.defaultExpr ?? (prop.required ? requiredStoryValue(prop) : undefined);
    if (value !== undefined) lines.push(`    ${prop.name}: ${value},`);
  }
  return lines;
}

function requiredStoryValue(prop: PropSpec): string | undefined {
  switch (prop.fieldType) {
    case 'boolean':
      return 'false';
    case 'number':
      return '0';
    case 'array':
      return '[]';
    case 'object':
      return '{}';
    case 'enum': {
      const first = prop.type.split('|')[0]?.trim();
      return first && first.startsWith("'") ? first : "'Example'";
    }
    case 'text':
    case 'richText':
    case 'image':
    case 'link':
    case 'token':
      return prop.source === 'src' ? "'/placeholder-media'" : "'Example'";
    default:
      return undefined;
  }
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}
