/**
 * Generated by @facadeur/codegen-react from the "form-controls" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { FormControlsProps } from './types';
import { FormControlsSection } from '../FormControlsSection';

export function FormControls({ nodeId, className }: FormControlsProps) {
  return (
    <div
      data-component="form-controls"
      data-node={nodeId}
      className={[styles.f_root_95igqt, className].filter(Boolean).join(' ')}
    >
      <FormControlsSection
        nodeId="form-controls-section"
        className={styles.f_form_controls_section_qic7ea}
      />
    </div>
  );
}
