/**
 * Generated by @facadeur/codegen-react from the "form-controls" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import './style.css';
import type { FormControlsProps } from './types';
import { FormControlsSection } from '../FormControlsSection';

export function FormControls({ nodeId, className }: FormControlsProps) {
  return (
    <div data-component="form-controls" data-node={nodeId} className={className}>
      <FormControlsSection nodeId="form-controls-section" />
    </div>
  );
}
