/**
 * Generated by @facadeur/codegen-react from the "form-controls" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { FormControls } from './component';
export type { FormControlsProps } from './types';
