/**
 * Generated by @facadeur/codegen-react from the "form-controls" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export interface FormControlsData {
  formFields?: {
    id: string;
    kind: 'input' | 'textarea' | 'select' | 'toggle';
    label: string;
    value?: string;
    placeholder?: string;
    hint?: string;
    rows?: number;
  }[];
  type?: string;
  hint?: string;
  icon?: string;
  hasIcon?: boolean;
  disabled?: boolean;
  placeholder?: string;
  name?: string;
  rows?: number;
  label?: string;
  value?: string;
}

export interface FormControlsProps extends ComponentProps, FormControlsData {}
