/**
 * Generated by @facadeur/codegen-react from the "form-segmented" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import './style.css';
import type { FormSegmentedProps } from './types';

export function FormSegmented({ label, state = 'start', nodeId, className }: FormSegmentedProps) {
  return (
    <div
      data-component="form-segmented"
      data-node={nodeId}
      data-variant-state={state}
      className={className}
    >
      <span data-node="label">{label}</span>
      <div data-node="options">
        <span data-node="start">Start</span>
        <span data-node="center">Center</span>
        <span data-node="end">End</span>
      </div>
    </div>
  );
}
