/**
 * Generated by @facadeur/codegen-react from the "form-segmented" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import styles from './style.module.css';
import type { FormSegmentedProps } from './types';

export function FormSegmented({ label, state = 'start', nodeId, className }: FormSegmentedProps) {
  return (
    <div
      data-component="form-segmented"
      data-node={nodeId}
      data-variant-state={state}
      className={[styles.f_root_95igqt, className].filter(Boolean).join(' ')}
    >
      <span data-node="label" className={styles.f_label_1wf4cn1}>
        {label}
      </span>
      <div data-node="options" className={styles.f_options_1ucvqn9}>
        <span data-node="start" className={styles.f_start_s2jf1b}>
          Start
        </span>
        <span data-node="center" className={styles.f_center_1jezyc}>
          Center
        </span>
        <span data-node="end" className={styles.f_end_tkd2ga}>
          End
        </span>
      </div>
    </div>
  );
}
