/**
 * Generated by @facadeur/codegen-react from the "form-segmented" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export { FormSegmented } from './component';
export type { FormSegmentedProps, FormSegmentedData, FormSegmentedState } from './types';
