/**
 * Generated by @facadeur/codegen-react from the "form-segmented" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

import type { ComponentProps } from '../../contracts';

export type FormSegmentedState = 'start' | 'center' | 'end';

export interface FormSegmentedData {
  label?: string;
}

export interface FormSegmentedProps extends ComponentProps, FormSegmentedData {
  state?: FormSegmentedState;
}
