/**
 * Generated by @facadeur/codegen-react from the "form-segmented" document.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

export type FormSegmentedState = 'start' | 'center' | 'end';

export interface FormSegmentedProps {
  label?: string;
  state?: FormSegmentedState;
  /** Instance id. Sets `data-node` so a parent style rule can address this element. */
  nodeId?: string;
  className?: string;
}
