export function renderSharedContracts() {
  return `/**
 * Generated by @facadeur/codegen-react.
 * The facadeur JSON is the source of truth. Do not edit by hand.
 */

/** Current loop values; parent follows loop boundaries, not component boundaries. */
export interface DataContext {
  item: unknown;
  index: number;
  parent?: DataContext;
}

export interface ComponentProps {
  className?: string;
  /** Runtime loop context. Components read or forward it only when needed. */
  context?: DataContext;
}

export interface LabelProps {
  label?: string;
}

export interface ValueProps<TValue = string> {
  value?: TValue;
}

export interface CommitProps<TPayload> {
  onCommit?: (payload: TPayload) => void;
}
`;
}
