import { quote } from '../names.js';
import type { Attr, ComponentImport, ElementNode, PropSpec, VariantTypeSpec } from './types.js';

export function printFile(file: {
  id: string;
  component: string;
  props: PropSpec[];
  variantTypes: VariantTypeSpec[];
  imports: ComponentImport[];
  usesCssProperties: boolean;
  usedProps: Set<string>;
  body: string;
}): string {
  const lines = [
    '/**',
    ` * Generated by @facadeur/codegen-react from the "${file.id}" document.`,
    ' * The facadeur JSON is the source of truth. Do not edit by hand.',
    ' */',
    '',
  ];
  if (file.usesCssProperties) {
    lines.push(`import type { CSSProperties } from 'react';`, '');
  }
  for (const spec of file.imports) {
    if (spec.name === file.component) continue;
    lines.push(`import { ${spec.name} } from ${quote(spec.from)};`);
  }
  if (file.imports.some((spec) => spec.name !== file.component)) lines.push('');
  for (const variant of file.variantTypes) {
    lines.push(`export type ${variant.name} = ${variant.union};`);
  }
  if (file.variantTypes.length) lines.push('');
  lines.push(`export interface ${file.component}Props {`);
  for (const prop of file.props) {
    lines.push(`  ${prop.name}?: ${prop.type};`);
  }
  lines.push(
    '  /** Instance id. Sets `data-node` so a parent style rule can address this element. */',
  );
  lines.push('  nodeId?: string;');
  lines.push('  className?: string;');
  lines.push('}');
  lines.push('');
  lines.push(`export function ${file.component}({`);
  for (const prop of file.props) {
    if (prop.fieldType !== 'variant' && !file.usedProps.has(prop.name)) continue;
    const initializer = prop.defaultExpr !== undefined ? ` = ${prop.defaultExpr}` : '';
    lines.push(`  ${prop.name}${initializer},`);
  }
  lines.push('  nodeId,');
  lines.push('  className,');
  lines.push(`}: ${file.component}Props) {`);
  lines.push('  return (');
  lines.push(file.body);
  lines.push('  );');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

export function printElement(element: ElementNode, indent: number): string {
  const pad = '  '.repeat(indent);
  const attrs = element.attrs.map(printAttr);
  const inlineAttrs = attrs.length ? ` ${attrs.join(' ')}` : '';
  if (element.void || element.children.length === 0) {
    const one = `${pad}<${element.tag}${inlineAttrs} />`;
    if (attrs.length <= 3 && one.length <= 100) return one;
    return `${pad}<${element.tag}\n${attrs.map((attr) => `${pad}  ${attr}`).join('\n')}\n${pad}/>`;
  }
  const only = element.children[0];
  if (element.children.length === 1 && only && 'text' in only && !only.text.includes('\n')) {
    const one = `${pad}<${element.tag}${inlineAttrs}>${only.text}</${element.tag}>`;
    if (attrs.length <= 2 && one.length <= 100) return one;
  }
  const open =
    attrs.length === 0
      ? `${pad}<${element.tag}>`
      : `${pad}<${element.tag}\n${attrs.map((attr) => `${pad}  ${attr}`).join('\n')}\n${pad}>`;
  const children = element.children
    .map((child) => ('text' in child ? `${pad}  ${child.text}` : printElement(child, indent + 1)))
    .join('\n');
  return `${open}\n${children}\n${pad}</${element.tag}>`;
}

function printAttr(attr: Attr): string {
  if (attr.value.kind === 'bool') {
    return attr.value.value ? attr.name : `${attr.name}={false}`;
  }
  if (attr.value.kind === 'literal') return `${attr.name}=${quote(attr.value.value)}`;
  return `${attr.name}={${attr.value.code}}`;
}
