import { quote } from '../names.js';
import { childFieldsPropType } from './child-fields.js';
import type { Attr, ComponentImport, ElementNode, PropSpec, VariantTypeSpec } from './types.js';

interface PrintedComponent {
  id: string;
  component: string;
  props: PropSpec[];
  variantTypes: VariantTypeSpec[];
  imports: ComponentImport[];
  usesCssProperties: boolean;
  acceptsChildFields: boolean;
  childFieldsPropName: string;
  usedProps: Set<string>;
  body: string;
}

export function printTypesFile(file: PrintedComponent): string {
  const lines = generatedBanner(file.id);
  if (file.usesCssProperties) {
    lines.push(`import type { CSSProperties } from 'react';`, '');
  }
  for (const variant of file.variantTypes) {
    lines.push(`export type ${variant.name} = ${variant.union};`);
  }
  if (file.variantTypes.length) lines.push('');
  lines.push(`export interface ${file.component}Props {`);
  for (const prop of file.props) {
    lines.push(`  ${prop.name}${prop.required ? '' : '?'}: ${prop.type};`);
  }
  lines.push(
    '  /** Instance id. Sets `data-node` so a parent style rule can address this element. */',
  );
  lines.push('  nodeId?: string;');
  lines.push('  className?: string;');
  if (file.acceptsChildFields) {
    lines.push(`  ${file.childFieldsPropName}?: ${childFieldsPropType};`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

export function printComponentFile(file: PrintedComponent): string {
  const lines = generatedBanner(file.id);
  if (file.props.some((prop) => prop.fieldType === 'event')) lines.push("'use client';", '');
  lines.push("import styles from './style.module.css';");
  if (file.usesCssProperties) lines.push(`import type { CSSProperties } from 'react';`);
  lines.push(`import type { ${file.component}Props } from './types';`);
  for (const spec of file.imports) {
    if (spec.name === file.component) continue;
    lines.push(`import { ${spec.name} } from ${quote(spec.from)};`);
  }
  lines.push('');
  lines.push(`export function ${file.component}({`);
  for (const prop of file.props) {
    if (prop.fieldType !== 'variant' && !file.usedProps.has(prop.name)) continue;
    const initializer =
      prop.variantDefaultExpr !== undefined
        ? ` = ${prop.variantDefaultExpr}`
        : prop.defaultExpr !== undefined
          ? ` = ${prop.defaultExpr}`
          : '';
    lines.push(`  ${prop.name}${initializer},`);
  }
  lines.push('  nodeId,');
  lines.push('  className,');
  if (file.acceptsChildFields) lines.push(`  ${file.childFieldsPropName},`);
  lines.push(`}: ${file.component}Props) {`);
  lines.push('  return (');
  lines.push(file.body);
  lines.push('  );');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

export function printComponentIndex(file: PrintedComponent): string {
  const types = [`${file.component}Props`, ...file.variantTypes.map((variant) => variant.name)];
  return [
    ...generatedBanner(file.id),
    `export { ${file.component} } from './component';`,
    `export type { ${types.join(', ')} } from './types';`,
    '',
  ].join('\n');
}

function generatedBanner(id: string): string[] {
  return [
    '/**',
    ` * Generated by @facadeur/codegen-react from the "${id}" document.`,
    ' * The facadeur JSON is the source of truth. Do not edit by hand.',
    ' */',
    '',
  ];
}

export function printElement(element: ElementNode, indent: number): string {
  const pad = '  '.repeat(indent);
  const attrs = [
    ...element.attrs,
    ...(element.repeat
      ? [{ name: 'key', value: { kind: 'expr' as const, code: element.repeat.key } }]
      : []),
  ].map(printAttr);
  const inlineAttrs = attrs.length ? ` ${attrs.join(' ')}` : '';
  if (element.void || element.children.length === 0) {
    const one = `${pad}<${element.tag}${inlineAttrs} />`;
    const rendered =
      attrs.length <= 3 && one.length <= 100
        ? one
        : `${pad}<${element.tag}\n${attrs.map((attr) => `${pad}  ${attr}`).join('\n')}\n${pad}/>`;
    return wrapRepeat(element.repeat, wrapCondition(element.condition, rendered, pad), pad);
  }
  const only = element.children[0];
  if (element.children.length === 1 && only && 'text' in only && !only.text.includes('\n')) {
    const one = `${pad}<${element.tag}${inlineAttrs}>${only.text}</${element.tag}>`;
    if (attrs.length <= 2 && one.length <= 100) {
      return wrapRepeat(element.repeat, wrapCondition(element.condition, one, pad), pad);
    }
  }
  const open =
    attrs.length === 0
      ? `${pad}<${element.tag}>`
      : `${pad}<${element.tag}\n${attrs.map((attr) => `${pad}  ${attr}`).join('\n')}\n${pad}>`;
  const children = element.children
    .map((child) => ('text' in child ? `${pad}  ${child.text}` : printElement(child, indent + 1)))
    .join('\n');
  return wrapRepeat(
    element.repeat,
    wrapCondition(element.condition, `${open}\n${children}\n${pad}</${element.tag}>`, pad),
    pad,
  );
}

function wrapRepeat(repeat: ElementNode['repeat'], body: string, pad: string): string {
  if (!repeat) return body;
  const indented = body
    .split('\n')
    .map((line) => `${pad}  ${line.slice(pad.length)}`)
    .join('\n');
  return `${pad}{${repeat.source}.map((${repeat.item}, ${repeat.index}) => (\n${indented}\n${pad}))}`;
}

function wrapCondition(condition: string | undefined, body: string, pad: string): string {
  if (!condition) return body;
  const indented = body
    .split('\n')
    .map((line) => `${pad}  ${line.slice(pad.length)}`)
    .join('\n');
  return `${pad}{${condition} && (\n${indented}\n${pad})}`;
}

function printAttr(attr: Attr): string {
  if (attr.value.kind === 'bool') {
    return attr.value.value ? attr.name : `${attr.name}={false}`;
  }
  if (attr.value.kind === 'literal') return `${attr.name}=${quote(attr.value.value)}`;
  return `${attr.name}={${attr.value.code}}`;
}
